/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 05 22:39:31 GMT 2018
 */

package com.actionbarsherlock.widget;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import android.content.Context;
import android.content.Intent;
import com.actionbarsherlock.internal.view.menu.SubMenuWrapper;
import com.actionbarsherlock.view.SubMenu;
import com.actionbarsherlock.widget.ShareActionProvider;
import com.xtremelabs.robolectric.tester.android.view.TestSubMenu;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ShareActionProvider_ESTest extends ShareActionProvider_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ShareActionProvider shareActionProvider0 = new ShareActionProvider((Context) null);
      shareActionProvider0.setShareHistoryFileName("ka5D38o4VSRp o54");
      ShareActionProvider.OnShareTargetSelectedListener shareActionProvider_OnShareTargetSelectedListener0 = mock(ShareActionProvider.OnShareTargetSelectedListener.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        shareActionProvider0.setOnShareTargetSelectedListener(shareActionProvider_OnShareTargetSelectedListener0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Stub!
         //
         verifyException("android.database.Observable", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ShareActionProvider shareActionProvider0 = new ShareActionProvider((Context) null);
      shareActionProvider0.setShareHistoryFileName("[&");
      // Undeclared exception!
      try { 
        shareActionProvider0.setShareIntent((Intent) null);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Stub!
         //
         verifyException("android.database.Observable", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ShareActionProvider shareActionProvider0 = new ShareActionProvider((Context) null);
      shareActionProvider0.setShareHistoryFileName("com.actionbarsherlock.widget.ShareActionProvider$ShareAcitivityChooserModelPolicy");
      // Undeclared exception!
      try { 
        shareActionProvider0.onCreateActionView();
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Stub!
         //
         verifyException("android.database.Observable", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ShareActionProvider shareActionProvider0 = new ShareActionProvider((Context) null);
      shareActionProvider0.setOnShareTargetSelectedListener((ShareActionProvider.OnShareTargetSelectedListener) null);
      assertFalse(shareActionProvider0.onPerformDefaultAction());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ShareActionProvider shareActionProvider0 = new ShareActionProvider((Context) null);
      TestSubMenu testSubMenu0 = new TestSubMenu();
      SubMenuWrapper subMenuWrapper0 = new SubMenuWrapper(testSubMenu0);
      // Undeclared exception!
      try { 
        shareActionProvider0.onPrepareSubMenu(subMenuWrapper0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Stub!
         //
         verifyException("android.database.Observable", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      ShareActionProvider shareActionProvider0 = new ShareActionProvider((Context) null);
      // Undeclared exception!
      try { 
        shareActionProvider0.onPrepareSubMenu((SubMenu) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.actionbarsherlock.widget.ShareActionProvider", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      ShareActionProvider shareActionProvider0 = new ShareActionProvider((Context) null);
      boolean boolean0 = shareActionProvider0.hasSubMenu();
      assertTrue(boolean0);
  }
}
