/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Mon Nov 05 22:22:33 GMT 2018
 */

package com.actionbarsherlock.internal.nineoldandroids.view;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class NineViewGroup_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.actionbarsherlock.internal.nineoldandroids.view.NineViewGroup"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    /*No java.lang.System property to set*/
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(NineViewGroup_ESTest_scaffolding.class.getClassLoader() ,
      "android.view.ViewParent",
      "com.actionbarsherlock.internal.nineoldandroids.view.NineViewGroup",
      "android.view.KeyEvent$Callback",
      "android.graphics.drawable.Drawable$Callback",
      "android.view.View",
      "com.actionbarsherlock.internal.nineoldandroids.view.animation.AnimatorProxy",
      "android.view.animation.Animation",
      "android.view.ViewGroup",
      "android.view.ViewManager",
      "android.view.accessibility.AccessibilityEventSource"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(NineViewGroup_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "android.view.View",
      "android.view.ViewGroup",
      "com.actionbarsherlock.internal.nineoldandroids.view.NineViewGroup",
      "android.os.Build$VERSION",
      "android.view.animation.Animation",
      "com.actionbarsherlock.internal.nineoldandroids.view.animation.AnimatorProxy",
      "android.content.Context",
      "android.content.ContextWrapper",
      "android.view.ContextThemeWrapper",
      "android.app.Activity",
      "android.app.NativeActivity",
      "android.app.ListActivity",
      "android.text.SpannableStringBuilder",
      "android.accounts.AccountAuthenticatorActivity",
      "android.app.ExpandableListActivity",
      "android.app.AliasActivity",
      "android.content.pm.PackageItemInfo",
      "android.content.pm.ComponentInfo",
      "android.content.pm.ProviderInfo",
      "com.xtremelabs.robolectric.tester.android.util.TestAttributeSet",
      "com.actionbarsherlock.app.ActionBar",
      "com.actionbarsherlock.internal.app.ActionBarWrapper",
      "android.widget.BaseAdapter",
      "android.widget.ArrayAdapter",
      "android.app.Fragment",
      "android.app.DialogFragment",
      "android.content.ContentProvider",
      "android.content.SearchRecentSuggestionsProvider",
      "android.view.animation.DecelerateInterpolator",
      "com.actionbarsherlock.internal.widget.AbsActionBarView",
      "com.xtremelabs.robolectric.res.ResourceExtractor",
      "com.xtremelabs.robolectric.res.XmlLoader",
      "com.xtremelabs.robolectric.res.AttrResourceLoader",
      "android.text.SpannableStringInternal",
      "android.text.SpannableString",
      "android.content.Loader",
      "android.view.View$MeasureSpec",
      "android.view.ViewGroup$LayoutParams",
      "android.util.DisplayMetrics",
      "com.actionbarsherlock.internal.nineoldandroids.animation.Animator",
      "com.actionbarsherlock.internal.nineoldandroids.animation.ValueAnimator$1",
      "com.actionbarsherlock.internal.nineoldandroids.animation.ValueAnimator$2",
      "com.actionbarsherlock.internal.nineoldandroids.animation.ValueAnimator$3",
      "com.actionbarsherlock.internal.nineoldandroids.animation.ValueAnimator$4",
      "com.actionbarsherlock.internal.nineoldandroids.animation.ValueAnimator$5",
      "android.view.animation.AccelerateDecelerateInterpolator",
      "com.actionbarsherlock.internal.nineoldandroids.animation.ValueAnimator",
      "android.os.Parcel",
      "android.graphics.drawable.Drawable",
      "android.graphics.drawable.DrawableContainer",
      "android.graphics.drawable.StateListDrawable",
      "android.content.res.Configuration",
      "com.xtremelabs.robolectric.RobolectricConfig",
      "android.content.pm.PackageInfo",
      "android.content.res.Resources",
      "android.graphics.Region",
      "com.actionbarsherlock.internal.app.ActionBarImpl",
      "android.os.Handler",
      "android.content.MutableContextWrapper",
      "android.database.DefaultDatabaseErrorHandler",
      "android.content.pm.PackageManager",
      "com.xtremelabs.robolectric.tester.android.content.pm.StubPackageManager",
      "com.xtremelabs.robolectric.res.RobolectricPackageManager",
      "android.app.Dialog",
      "android.app.AlertDialog",
      "android.app.ProgressDialog",
      "android.app.DatePickerDialog",
      "android.database.sqlite.SQLiteClosable",
      "android.database.sqlite.SQLiteDatabase",
      "android.app.TimePickerDialog",
      "android.text.SpannedString"
    );
  }
}
