/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Mon Nov 05 22:38:28 GMT 2018
 */

package com.actionbarsherlock.internal.app;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class ActionBarWrapper_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.actionbarsherlock.internal.app.ActionBarWrapper"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {} 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "Cp1252"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\Thiago\\AppData\\Local\\Temp\\"); 
    java.lang.System.setProperty("user.country", "US"); 
    java.lang.System.setProperty("user.dir", "C:\\Users\\Thiago\\Documents\\Calculadora\\Calculadora-de-Tributos-PJ\\ActionBarSherlock-Library"); 
    java.lang.System.setProperty("user.home", "C:\\Users\\Thiago"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "Thiago"); 
    java.lang.System.setProperty("user.timezone", "America/Sao_Paulo"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(ActionBarWrapper_ESTest_scaffolding.class.getClassLoader() ,
      "android.os.Bundle",
      "android.content.IntentSender$SendIntentException",
      "android.net.Uri",
      "android.view.View$AccessibilityDelegate",
      "android.content.ComponentCallbacks",
      "android.graphics.drawable.Drawable",
      "android.view.TouchDelegate",
      "android.view.View$MeasureSpec",
      "android.util.Property",
      "com.actionbarsherlock.app.ActionBar$OnNavigationListener",
      "android.support.v4.app._ActionBarSherlockTrojanHorse",
      "android.database.sqlite.SQLiteDatabase",
      "android.graphics.drawable.Drawable$ConstantState",
      "android.view.View$OnSystemUiVisibilityChangeListener",
      "android.os.Handler",
      "android.os.Looper",
      "android.graphics.Canvas",
      "android.view.accessibility.AccessibilityEvent",
      "org.xmlpull.v1.XmlPullParser",
      "com.actionbarsherlock.ActionBarSherlock$OnPreparePanelListener",
      "android.view.DragEvent",
      "android.content.res.Resources$NotFoundException",
      "android.content.IntentFilter",
      "android.view.View$OnGenericMotionListener",
      "android.graphics.Region",
      "android.view.View$OnLayoutChangeListener",
      "com.actionbarsherlock.internal.app.ActionBarWrapper",
      "android.view.View$OnAttachStateChangeListener",
      "android.graphics.Paint",
      "android.view.accessibility.AccessibilityEventSource",
      "android.app.FragmentManager",
      "android.view.ViewParent",
      "com.actionbarsherlock.app.ActionBar$Tab",
      "android.content.IntentSender$OnFinished",
      "android.view.View$OnClickListener",
      "android.content.pm.PackageManager$NameNotFoundException",
      "com.actionbarsherlock.app.ActionBar",
      "com.actionbarsherlock.app.ActionBar$LayoutParams",
      "android.app.Dialog",
      "android.app.FragmentTransaction",
      "android.content.IntentSender",
      "android.content.res.AssetManager",
      "android.view.MenuInflater",
      "android.view.Menu",
      "android.app.ActionBar$OnMenuVisibilityListener",
      "android.content.ContextWrapper",
      "android.content.res.Resources$Theme",
      "android.graphics.ColorFilter",
      "android.app.Fragment",
      "android.widget.SpinnerAdapter",
      "android.os.Parcelable",
      "com.actionbarsherlock.ActionBarSherlock$OnActionModeStartedListener",
      "android.view.KeyEvent$Callback",
      "android.app.ActionBar$OnNavigationListener",
      "android.content.ComponentName",
      "android.graphics.PorterDuff$Mode",
      "android.view.Window$Callback",
      "android.content.ComponentCallbacks2",
      "android.content.SharedPreferences",
      "android.util.TypedValue",
      "android.view.ViewGroup$MarginLayoutParams",
      "android.content.res.Configuration",
      "android.view.View$OnCreateContextMenuListener",
      "android.view.View$BaseSavedState",
      "android.graphics.Rect",
      "android.view.ActionMode",
      "android.content.pm.PackageManager",
      "android.graphics.drawable.Drawable$Callback",
      "com.actionbarsherlock.ActionBarSherlock$OnMenuItemSelectedListener",
      "android.view.WindowManager",
      "android.app.PendingIntent",
      "com.actionbarsherlock.internal.app.ActionBarWrapper$TabWrapper",
      "android.os.IBinder",
      "android.view.KeyEvent$DispatcherState",
      "android.util.AttributeSet",
      "android.content.ContentResolver",
      "android.view.ContextThemeWrapper",
      "android.database.DatabaseErrorHandler",
      "android.content.ServiceConnection",
      "android.view.View",
      "android.view.animation.Animation",
      "android.app.ActionBar$LayoutParams",
      "android.graphics.Matrix",
      "android.database.DataSetObserver",
      "com.actionbarsherlock.app.SherlockFragmentActivity",
      "android.view.View$OnLongClickListener",
      "android.app.ActionBar$Tab",
      "android.view.ViewGroup$LayoutParams",
      "android.util.AndroidException",
      "android.view.InputEvent",
      "android.text.InputType",
      "android.graphics.PorterDuff",
      "android.content.BroadcastReceiver",
      "android.view.ViewGroup",
      "org.xmlpull.v1.XmlPullParserException",
      "android.util.SparseArray",
      "android.app.Application",
      "android.support.v4.app.FragmentActivity",
      "android.view.accessibility.AccessibilityRecord",
      "android.view.ViewPropertyAnimator",
      "android.view.LayoutInflater$Factory2",
      "android.content.pm.ApplicationInfo",
      "android.view.Window",
      "android.view.inputmethod.EditorInfo",
      "android.graphics.BitmapFactory$Options",
      "android.content.Context",
      "android.view.ContextMenu",
      "android.view.accessibility.AccessibilityNodeInfo",
      "android.view.KeyEvent",
      "android.widget.Adapter",
      "android.view.LayoutInflater$Factory",
      "android.view.inputmethod.InputConnection",
      "com.actionbarsherlock.app.ActionBar$TabListener",
      "android.app.ActionBar$TabListener",
      "android.content.Intent",
      "android.content.res.TypedArray",
      "android.view.MenuItem",
      "android.view.ActionMode$Callback",
      "android.content.ClipData",
      "android.view.MotionEvent",
      "android.view.WindowManager$LayoutParams",
      "android.app.LoaderManager",
      "android.database.Cursor",
      "android.content.DialogInterface",
      "android.app.ActionBar",
      "android.view.View$OnKeyListener",
      "android.view.LayoutInflater",
      "android.view.AbsSavedState",
      "android.graphics.Point",
      "android.content.pm.PackageItemInfo",
      "android.database.sqlite.SQLiteDatabase$CursorFactory",
      "android.view.View$DragShadowBuilder",
      "android.graphics.Bitmap",
      "android.view.View$OnFocusChangeListener",
      "com.actionbarsherlock.ActionBarSherlock$OnActionModeFinishedListener",
      "android.view.ViewTreeObserver",
      "com.actionbarsherlock.ActionBarSherlock$OnCreatePanelMenuListener",
      "android.database.sqlite.SQLiteClosable",
      "com.actionbarsherlock.app.ActionBar$OnMenuVisibilityListener",
      "android.app.Activity",
      "android.support.v4.app.FragmentTransaction",
      "android.view.View$OnTouchListener",
      "android.view.View$OnHoverListener",
      "android.view.ContextMenu$ContextMenuInfo",
      "android.content.res.Resources",
      "android.view.ViewManager",
      "android.view.View$OnDragListener"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException { 
    mock(Class.forName("android.app.ActionBar", false, ActionBarWrapper_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("android.app.ActionBar$Tab", false, ActionBarWrapper_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("android.app.Activity", false, ActionBarWrapper_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("android.app.FragmentTransaction", false, ActionBarWrapper_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("android.content.Context", false, ActionBarWrapper_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("android.graphics.drawable.Drawable", false, ActionBarWrapper_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("android.view.View", false, ActionBarWrapper_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("android.widget.SpinnerAdapter", false, ActionBarWrapper_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("com.actionbarsherlock.app.ActionBar$LayoutParams", false, ActionBarWrapper_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("com.actionbarsherlock.app.ActionBar$OnMenuVisibilityListener", false, ActionBarWrapper_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("com.actionbarsherlock.app.ActionBar$OnNavigationListener", false, ActionBarWrapper_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("com.actionbarsherlock.app.ActionBar$TabListener", false, ActionBarWrapper_ESTest_scaffolding.class.getClassLoader()));
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(ActionBarWrapper_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.actionbarsherlock.app.ActionBar",
      "com.actionbarsherlock.internal.app.ActionBarWrapper",
      "com.actionbarsherlock.app.ActionBar$Tab",
      "com.actionbarsherlock.internal.app.ActionBarWrapper$TabWrapper",
      "android.content.Context",
      "android.content.ContextWrapper",
      "android.view.ContextThemeWrapper",
      "android.app.Activity",
      "android.app.ActionBar$Tab",
      "android.view.View",
      "android.view.ViewGroup$LayoutParams",
      "android.view.ViewGroup$MarginLayoutParams",
      "com.actionbarsherlock.app.ActionBar$LayoutParams",
      "android.app.ActionBar$LayoutParams",
      "android.app.FragmentTransaction",
      "android.app.ActionBar",
      "android.graphics.drawable.Drawable"
    );
  }
}
