/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 05 22:13:23 GMT 2018
 */

package com.actionbarsherlock.view;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import android.content.Context;
import com.actionbarsherlock.internal.view.menu.SubMenuWrapper;
import com.actionbarsherlock.view.MenuInflater;
import com.xtremelabs.robolectric.tester.android.view.TestSubMenu;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MenuInflater_ESTest extends MenuInflater_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MenuInflater menuInflater0 = new MenuInflater((Context) null);
      TestSubMenu testSubMenu0 = new TestSubMenu();
      SubMenuWrapper subMenuWrapper0 = new SubMenuWrapper(testSubMenu0);
      // Undeclared exception!
      try { 
        menuInflater0.inflate(0, subMenuWrapper0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.actionbarsherlock.view.MenuInflater", e);
      }
  }
}
