/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 05 21:22:50 GMT 2018
 */

package com.actionbarsherlock.internal.view.menu;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import android.content.Context;
import com.actionbarsherlock.internal.view.menu.ActionMenuPresenter;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ActionMenuPresenter_ESTest extends ActionMenuPresenter_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try { 
        ActionMenuPresenter.reserveOverflow((Context) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.actionbarsherlock.internal.view.menu.ActionMenuPresenter", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ActionMenuPresenter actionMenuPresenter0 = null;
      try {
        actionMenuPresenter0 = new ActionMenuPresenter((Context) null);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Stub!
         //
         verifyException("android.view.LayoutInflater", e);
      }
  }
}
