/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Mon Nov 05 22:34:41 GMT 2018
 */

package com.actionbarsherlock.internal.view.menu;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class MenuItemWrapper_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.actionbarsherlock.internal.view.menu.MenuItemWrapper"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {} 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "Cp1252"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\Thiago\\AppData\\Local\\Temp\\"); 
    java.lang.System.setProperty("user.country", "US"); 
    java.lang.System.setProperty("user.dir", "C:\\Users\\Thiago\\Documents\\Calculadora\\Calculadora-de-Tributos-PJ\\ActionBarSherlock-Library"); 
    java.lang.System.setProperty("user.home", "C:\\Users\\Thiago"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "Thiago"); 
    java.lang.System.setProperty("user.timezone", "America/Sao_Paulo"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(MenuItemWrapper_ESTest_scaffolding.class.getClassLoader() ,
      "android.graphics.Rect",
      "android.os.Bundle",
      "android.content.pm.PackageManager",
      "android.graphics.drawable.Drawable$Callback",
      "android.net.Uri",
      "android.view.MenuItem$OnActionExpandListener",
      "android.graphics.drawable.Drawable",
      "com.actionbarsherlock.view.MenuItem",
      "android.graphics.drawable.Drawable$ConstantState",
      "com.actionbarsherlock.view.SubMenu",
      "android.util.AttributeSet",
      "android.content.ContentResolver",
      "android.content.pm.ActivityInfo",
      "android.view.View",
      "com.actionbarsherlock.widget.ActivityChooserView",
      "android.graphics.Canvas",
      "com.actionbarsherlock.internal.view.ActionProviderWrapper",
      "org.xmlpull.v1.XmlPullParser",
      "android.view.MenuItem$OnMenuItemClickListener",
      "android.view.InputEvent",
      "com.xtremelabs.robolectric.tester.android.view.TestMenuItem",
      "com.actionbarsherlock.widget.ActivityChooserModel$OnChooseActivityListener",
      "android.view.SubMenu",
      "android.graphics.Region",
      "android.content.pm.ComponentInfo",
      "android.view.ActionProvider",
      "android.view.ViewGroup",
      "org.xmlpull.v1.XmlPullParserException",
      "com.actionbarsherlock.view.MenuItem$OnActionExpandListener",
      "com.actionbarsherlock.internal.view.menu.MenuItemWrapper",
      "android.view.accessibility.AccessibilityEventSource",
      "android.graphics.BitmapFactory$Options",
      "com.actionbarsherlock.view.MenuItem$OnMenuItemClickListener",
      "android.view.ContextMenu",
      "android.content.Context",
      "android.view.ViewParent",
      "android.view.KeyEvent",
      "com.actionbarsherlock.view.ActionProvider",
      "android.content.Intent",
      "com.actionbarsherlock.view.Menu",
      "com.xtremelabs.robolectric.tester.android.view.TestSubMenu",
      "android.os.Parcel",
      "android.view.MenuItem",
      "com.actionbarsherlock.widget.ShareActionProvider$OnShareTargetSelectedListener",
      "android.view.Menu",
      "com.actionbarsherlock.view.ActionProvider$SubUiVisibilityListener",
      "android.graphics.ColorFilter",
      "android.os.Parcelable",
      "com.actionbarsherlock.widget.ShareActionProvider",
      "android.view.KeyEvent$Callback",
      "android.content.ComponentName",
      "com.actionbarsherlock.widget.ActivityChooserModel$ActivityChooserModelClient",
      "com.xtremelabs.robolectric.tester.android.view.TestMenu",
      "com.actionbarsherlock.internal.view.menu.MenuItemWrapper$1",
      "android.graphics.PorterDuff$Mode",
      "android.content.pm.PackageItemInfo",
      "android.util.TypedValue",
      "com.actionbarsherlock.internal.view.menu.MenuWrapper",
      "com.actionbarsherlock.internal.view.menu.SubMenuWrapper",
      "com.actionbarsherlock.widget.ShareActionProvider$ShareMenuItemOnMenuItemClickListener",
      "android.view.ContextMenu$ContextMenuInfo",
      "android.view.ViewManager",
      "android.content.res.Resources"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException { 
    mock(Class.forName("com.actionbarsherlock.view.MenuItem$OnActionExpandListener", false, MenuItemWrapper_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("com.actionbarsherlock.view.MenuItem$OnMenuItemClickListener", false, MenuItemWrapper_ESTest_scaffolding.class.getClassLoader()));
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(MenuItemWrapper_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.actionbarsherlock.internal.view.menu.MenuItemWrapper",
      "com.actionbarsherlock.internal.view.menu.MenuItemWrapper$1",
      "com.xtremelabs.robolectric.tester.android.view.TestMenuItem",
      "com.xtremelabs.robolectric.tester.android.view.TestMenu",
      "com.xtremelabs.robolectric.tester.android.view.TestSubMenu",
      "android.content.Context",
      "android.content.ContextWrapper",
      "android.view.ActionProvider",
      "android.widget.ShareActionProvider",
      "android.view.accessibility.AccessibilityRecord",
      "android.view.accessibility.AccessibilityEvent",
      "android.graphics.drawable.Drawable",
      "android.graphics.drawable.DrawableContainer",
      "android.graphics.drawable.AnimationDrawable",
      "android.content.MutableContextWrapper",
      "android.net.Uri",
      "android.content.Intent",
      "android.graphics.drawable.StateListDrawable",
      "com.actionbarsherlock.view.ActionProvider",
      "com.actionbarsherlock.widget.ShareActionProvider",
      "com.actionbarsherlock.widget.ShareActionProvider$ShareMenuItemOnMenuItemClickListener",
      "com.actionbarsherlock.internal.view.ActionProviderWrapper",
      "android.view.ContextThemeWrapper",
      "android.app.Activity",
      "com.actionbarsherlock.ActionBarSherlock",
      "com.actionbarsherlock.internal.ActionBarSherlockCompat",
      "android.graphics.NinePatch",
      "android.graphics.drawable.NinePatchDrawable",
      "android.os.Build$VERSION",
      "com.actionbarsherlock.internal.view.menu.BaseMenuPresenter",
      "com.actionbarsherlock.internal.view.menu.ActionMenuPresenter",
      "com.actionbarsherlock.R$layout",
      "android.view.LayoutInflater",
      "android.graphics.drawable.ShapeDrawable",
      "android.graphics.drawable.PaintDrawable",
      "com.actionbarsherlock.internal.view.menu.MenuItemImpl",
      "android.view.View",
      "android.view.ViewGroup",
      "android.widget.RelativeLayout",
      "android.widget.DialerFilter",
      "android.graphics.drawable.ColorDrawable",
      "android.graphics.drawable.GradientDrawable",
      "com.actionbarsherlock.internal.view.menu.MenuWrapper",
      "com.actionbarsherlock.internal.view.menu.SubMenuWrapper",
      "com.xtremelabs.robolectric.tester.android.util.TestAttributeSet",
      "android.widget.SlidingDrawer",
      "android.graphics.drawable.LevelListDrawable",
      "android.widget.AdapterView",
      "android.widget.AbsListView",
      "android.widget.ListView",
      "android.widget.ExpandableListView",
      "android.graphics.drawable.InsetDrawable",
      "com.actionbarsherlock.R$styleable",
      "com.actionbarsherlock.internal.view.menu.MenuBuilder",
      "android.app.FragmentBreadCrumbs",
      "com.xtremelabs.robolectric.res.ResourceExtractor",
      "com.xtremelabs.robolectric.res.XmlLoader",
      "com.xtremelabs.robolectric.res.AttrResourceLoader",
      "android.widget.FrameLayout",
      "android.widget.DatePicker",
      "android.graphics.drawable.BitmapDrawable"
    );
  }
}
