/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Mon Nov 05 22:44:02 GMT 2018
 */

package com.actionbarsherlock.internal.view.menu;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class MenuWrapper_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.actionbarsherlock.internal.view.menu.MenuWrapper"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {} 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "Cp1252"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\Thiago\\AppData\\Local\\Temp\\"); 
    java.lang.System.setProperty("user.country", "US"); 
    java.lang.System.setProperty("user.dir", "C:\\Users\\Thiago\\Documents\\Calculadora\\Calculadora-de-Tributos-PJ\\ActionBarSherlock-Library"); 
    java.lang.System.setProperty("user.home", "C:\\Users\\Thiago"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "Thiago"); 
    java.lang.System.setProperty("user.timezone", "America/Sao_Paulo"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(MenuWrapper_ESTest_scaffolding.class.getClassLoader() ,
      "android.graphics.Rect",
      "android.os.Bundle",
      "android.content.pm.PackageManager",
      "android.graphics.drawable.Drawable$Callback",
      "android.net.Uri",
      "android.graphics.drawable.Drawable",
      "android.view.MenuItem$OnActionExpandListener",
      "android.view.KeyEvent$DispatcherState",
      "com.actionbarsherlock.view.MenuItem",
      "android.util.AndroidRuntimeException",
      "android.view.KeyCharacterMap$UnavailableException",
      "com.actionbarsherlock.view.SubMenu",
      "android.util.AttributeSet",
      "android.content.ContentResolver",
      "android.content.pm.ActivityInfo",
      "android.view.View",
      "com.actionbarsherlock.internal.view.ActionProviderWrapper",
      "org.xmlpull.v1.XmlPullParser",
      "android.view.MenuItem$OnMenuItemClickListener",
      "android.view.InputEvent",
      "android.view.KeyCharacterMap$KeyData",
      "android.view.SubMenu",
      "android.content.pm.ComponentInfo",
      "android.view.ActionProvider",
      "org.xmlpull.v1.XmlPullParserException",
      "com.actionbarsherlock.view.MenuItem$OnActionExpandListener",
      "com.actionbarsherlock.internal.view.menu.MenuItemWrapper",
      "android.view.accessibility.AccessibilityEventSource",
      "android.view.ContextMenu",
      "com.actionbarsherlock.view.MenuItem$OnMenuItemClickListener",
      "android.content.Context",
      "android.view.KeyEvent",
      "com.actionbarsherlock.view.ActionProvider",
      "android.content.Intent",
      "android.os.Parcelable$Creator",
      "com.actionbarsherlock.view.Menu",
      "android.os.Parcel",
      "android.view.MenuItem",
      "android.view.InputDevice",
      "android.view.Menu",
      "android.os.Parcelable",
      "android.view.KeyEvent$Callback",
      "android.content.ComponentName",
      "android.content.pm.PackageItemInfo",
      "com.actionbarsherlock.internal.view.menu.MenuWrapper",
      "android.view.KeyCharacterMap",
      "com.actionbarsherlock.internal.view.menu.SubMenuWrapper",
      "android.view.ContextMenu$ContextMenuInfo",
      "android.content.res.Resources"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException { 
    mock(Class.forName("android.content.ComponentName", false, MenuWrapper_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("android.content.Intent", false, MenuWrapper_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("android.view.KeyEvent", false, MenuWrapper_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("android.view.Menu", false, MenuWrapper_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("android.view.MenuItem", false, MenuWrapper_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("android.view.SubMenu", false, MenuWrapper_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("java.lang.CharSequence", false, MenuWrapper_ESTest_scaffolding.class.getClassLoader()));
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(MenuWrapper_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.actionbarsherlock.internal.view.menu.MenuWrapper",
      "com.actionbarsherlock.internal.view.menu.SubMenuWrapper",
      "android.content.ComponentName",
      "android.content.Intent",
      "com.actionbarsherlock.internal.view.menu.MenuItemWrapper",
      "android.view.InputEvent",
      "android.view.KeyEvent"
    );
  }
}
