/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Mon Nov 05 22:33:20 GMT 2018
 */

package com.actionbarsherlock.internal;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class ActionBarSherlockNative_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.actionbarsherlock.internal.ActionBarSherlockNative"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {} 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "Cp1252"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\Thiago\\AppData\\Local\\Temp\\"); 
    java.lang.System.setProperty("user.country", "US"); 
    java.lang.System.setProperty("user.dir", "C:\\Users\\Thiago\\Documents\\Calculadora\\Calculadora-de-Tributos-PJ\\ActionBarSherlock-Library"); 
    java.lang.System.setProperty("user.home", "C:\\Users\\Thiago"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "Thiago"); 
    java.lang.System.setProperty("user.timezone", "America/Sao_Paulo"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(ActionBarSherlockNative_ESTest_scaffolding.class.getClassLoader() ,
      "android.os.Bundle",
      "com.actionbarsherlock.internal.ActionBarSherlockNative$ActionModeWrapper",
      "android.graphics.drawable.Drawable$Callback",
      "com.actionbarsherlock.ActionBarSherlock$Implementation",
      "android.content.ComponentCallbacks",
      "com.actionbarsherlock.internal.ActionBarSherlockNative$ActionModeCallbackWrapper",
      "android.graphics.drawable.Drawable",
      "com.actionbarsherlock.view.MenuItem",
      "com.actionbarsherlock.app.ActionBar$OnNavigationListener",
      "com.actionbarsherlock.view.MenuInflater",
      "com.actionbarsherlock.view.SubMenu",
      "com.actionbarsherlock.internal.ActionBarSherlockCompat",
      "android.view.ContextThemeWrapper",
      "android.view.View",
      "android.view.MenuItem$OnMenuItemClickListener",
      "android.view.ViewGroup$LayoutParams",
      "android.view.InputEvent",
      "com.xtremelabs.robolectric.tester.android.view.TestMenuItem",
      "android.view.SubMenu",
      "android.view.ViewGroup",
      "com.actionbarsherlock.internal.app.ActionBarWrapper",
      "android.view.LayoutInflater$Factory2",
      "com.actionbarsherlock.internal.ActionBarSherlockNative",
      "android.view.accessibility.AccessibilityEventSource",
      "android.content.Context",
      "android.view.ViewParent",
      "android.view.KeyEvent",
      "android.widget.Adapter",
      "com.actionbarsherlock.app.ActionBar$Tab",
      "android.view.LayoutInflater$Factory",
      "com.actionbarsherlock.app.ActionBar",
      "com.actionbarsherlock.app.ActionBar$LayoutParams",
      "android.content.Intent",
      "com.actionbarsherlock.internal.view.menu.MenuPresenter$Callback",
      "com.actionbarsherlock.view.Menu",
      "com.actionbarsherlock.view.Window$Callback",
      "com.xtremelabs.robolectric.tester.android.view.TestSubMenu",
      "android.view.ActionMode$Callback",
      "android.view.MenuItem",
      "android.view.Menu",
      "android.app.ActionBar$OnMenuVisibilityListener",
      "android.content.ContextWrapper",
      "com.actionbarsherlock.internal.view.menu.MenuBuilder$Callback",
      "android.widget.SpinnerAdapter",
      "android.os.Parcelable",
      "android.view.KeyEvent$Callback",
      "android.app.ActionBar$OnNavigationListener",
      "android.content.ComponentName",
      "com.xtremelabs.robolectric.tester.android.view.TestMenu",
      "com.actionbarsherlock.view.ActionMode$Callback",
      "android.view.Window$Callback",
      "android.content.ComponentCallbacks2",
      "android.util.TypedValue",
      "com.actionbarsherlock.view.ActionMode",
      "com.actionbarsherlock.internal.view.menu.MenuWrapper",
      "android.content.res.Configuration",
      "android.view.ViewGroup$MarginLayoutParams",
      "com.actionbarsherlock.ActionBarSherlock",
      "com.actionbarsherlock.app.ActionBar$OnMenuVisibilityListener",
      "android.app.Activity",
      "android.view.View$OnCreateContextMenuListener",
      "android.view.ViewManager"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException { 
    mock(Class.forName("com.actionbarsherlock.view.ActionMode$Callback", false, ActionBarSherlockNative_ESTest_scaffolding.class.getClassLoader()));
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(ActionBarSherlockNative_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.actionbarsherlock.ActionBarSherlock",
      "com.actionbarsherlock.internal.ActionBarSherlockNative",
      "com.actionbarsherlock.view.ActionMode",
      "com.actionbarsherlock.internal.ActionBarSherlockNative$ActionModeWrapper",
      "com.actionbarsherlock.internal.ActionBarSherlockNative$ActionModeCallbackWrapper",
      "android.content.Context",
      "android.content.ContextWrapper",
      "android.view.ContextThemeWrapper",
      "android.app.Activity",
      "android.view.View",
      "android.view.ViewGroup",
      "android.app.FragmentBreadCrumbs",
      "android.app.Fragment",
      "android.util.TypedValue",
      "android.content.MutableContextWrapper",
      "android.content.res.Configuration",
      "android.os.Build$VERSION",
      "com.xtremelabs.robolectric.tester.android.view.TestMenuItem",
      "android.os.Bundle",
      "android.content.Intent",
      "com.xtremelabs.robolectric.tester.android.view.TestMenu",
      "com.xtremelabs.robolectric.tester.android.view.TestSubMenu",
      "android.content.ContentProvider",
      "android.content.SearchRecentSuggestionsProvider",
      "com.actionbarsherlock.internal.view.menu.MenuWrapper",
      "com.xtremelabs.robolectric.tester.android.util.TestAttributeSet",
      "android.widget.AdapterView",
      "android.widget.AbsListView",
      "android.widget.ListView",
      "android.widget.ExpandableListView",
      "android.graphics.drawable.Drawable",
      "android.graphics.drawable.DrawableContainer",
      "android.graphics.drawable.AnimationDrawable",
      "android.content.BroadcastReceiver",
      "android.appwidget.AppWidgetProvider",
      "android.view.InputEvent",
      "android.view.KeyEvent",
      "android.database.AbstractCursor",
      "android.database.MatrixCursor",
      "android.os.Parcel",
      "android.view.ViewGroup$LayoutParams",
      "android.view.WindowManager$LayoutParams",
      "android.content.ComponentName",
      "android.widget.AdapterViewAnimator",
      "android.widget.AdapterViewFlipper",
      "android.graphics.drawable.LevelListDrawable",
      "android.view.accessibility.AccessibilityRecord",
      "android.view.accessibility.AccessibilityEvent",
      "android.content.IntentSender",
      "android.widget.FrameLayout",
      "android.widget.DatePicker",
      "android.widget.CalendarView",
      "android.graphics.Bitmap",
      "android.widget.AbsoluteLayout",
      "android.webkit.WebView",
      "android.widget.RelativeLayout",
      "android.widget.DialerFilter",
      "android.graphics.drawable.GradientDrawable",
      "android.graphics.drawable.ShapeDrawable",
      "android.graphics.drawable.ColorDrawable",
      "android.gesture.GestureOverlayView",
      "android.appwidget.AppWidgetHostView",
      "com.actionbarsherlock.internal.view.menu.MenuItemWrapper",
      "com.xtremelabs.robolectric.res.ResourceExtractor",
      "com.xtremelabs.robolectric.res.XmlLoader",
      "com.xtremelabs.robolectric.res.AttrResourceLoader",
      "android.app.AliasActivity",
      "android.app.ListActivity",
      "android.accounts.AccountAuthenticatorActivity",
      "android.text.SpannableStringBuilder",
      "android.app.NativeActivity",
      "com.xtremelabs.robolectric.RobolectricConfig",
      "android.content.pm.PackageManager",
      "com.xtremelabs.robolectric.tester.android.content.pm.StubPackageManager",
      "com.xtremelabs.robolectric.res.RobolectricPackageManager",
      "android.renderscript.RenderScript",
      "android.renderscript.RenderScriptGL",
      "android.app.ExpandableListActivity",
      "android.app.ListFragment",
      "com.actionbarsherlock.app.ActionBar",
      "com.actionbarsherlock.internal.app.ActionBarImpl",
      "android.os.Handler",
      "android.content.pm.PackageItemInfo",
      "android.content.pm.ComponentInfo",
      "android.content.pm.ProviderInfo",
      "android.app.DialogFragment",
      "android.net.Uri",
      "android.content.ClipData$Item",
      "android.view.ActionProvider",
      "android.widget.ShareActionProvider",
      "android.widget.ViewAnimator",
      "android.content.Loader",
      "android.content.res.Resources",
      "android.view.TextureView",
      "android.preference.Preference",
      "android.preference.DialogPreference",
      "android.preference.EditTextPreference",
      "android.widget.ViewFlipper",
      "android.graphics.drawable.RotateDrawable",
      "android.widget.ImageView",
      "android.widget.QuickContactBadge",
      "android.widget.GridLayout",
      "android.widget.TimePicker",
      "android.os.Message",
      "android.app.Dialog",
      "android.app.AlertDialog",
      "android.app.TimePickerDialog",
      "android.text.SpannableStringInternal",
      "android.text.SpannedString",
      "com.actionbarsherlock.internal.app.ActionBarWrapper",
      "android.content.pm.PermissionInfo"
    );
  }
}
