/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Mon Nov 05 22:35:54 GMT 2018
 */

package com.actionbarsherlock.internal.nineoldandroids.animation;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class Animator_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.actionbarsherlock.internal.nineoldandroids.animation.Animator"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "Cp1252"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\Thiago\\AppData\\Local\\Temp\\"); 
    java.lang.System.setProperty("user.country", "US"); 
    java.lang.System.setProperty("user.dir", "C:\\Users\\Thiago\\Documents\\Calculadora\\Calculadora-de-Tributos-PJ\\ActionBarSherlock-Library"); 
    java.lang.System.setProperty("user.home", "C:\\Users\\Thiago"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "Thiago"); 
    java.lang.System.setProperty("user.timezone", "America/Sao_Paulo"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(Animator_ESTest_scaffolding.class.getClassLoader() ,
      "com.actionbarsherlock.internal.nineoldandroids.animation.Animator",
      "android.animation.TimeInterpolator",
      "com.actionbarsherlock.internal.nineoldandroids.animation.Animator$AnimatorListener",
      "android.view.animation.Interpolator",
      "com.actionbarsherlock.internal.nineoldandroids.animation.AnimatorSet$Builder",
      "com.actionbarsherlock.internal.nineoldandroids.animation.AnimatorSet"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(Animator_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.actionbarsherlock.internal.nineoldandroids.animation.Animator",
      "com.actionbarsherlock.internal.nineoldandroids.animation.ValueAnimator$1",
      "com.actionbarsherlock.internal.nineoldandroids.animation.ValueAnimator$2",
      "com.actionbarsherlock.internal.nineoldandroids.animation.ValueAnimator$3",
      "com.actionbarsherlock.internal.nineoldandroids.animation.ValueAnimator$4",
      "com.actionbarsherlock.internal.nineoldandroids.animation.ValueAnimator$5",
      "android.view.animation.AccelerateDecelerateInterpolator",
      "com.actionbarsherlock.internal.nineoldandroids.animation.ValueAnimator",
      "com.actionbarsherlock.internal.nineoldandroids.animation.AnimatorSet",
      "com.actionbarsherlock.internal.nineoldandroids.animation.AnimatorSet$Builder",
      "com.actionbarsherlock.internal.nineoldandroids.animation.AnimatorSet$Node",
      "com.actionbarsherlock.internal.nineoldandroids.animation.IntEvaluator",
      "com.actionbarsherlock.internal.nineoldandroids.animation.FloatEvaluator",
      "com.actionbarsherlock.internal.nineoldandroids.animation.PropertyValuesHolder",
      "android.content.Context",
      "android.content.ContextWrapper",
      "android.view.ContextThemeWrapper",
      "android.app.Activity",
      "android.app.AliasActivity",
      "com.actionbarsherlock.internal.nineoldandroids.animation.Keyframe",
      "com.actionbarsherlock.internal.nineoldandroids.animation.Keyframe$FloatKeyframe",
      "com.actionbarsherlock.internal.nineoldandroids.animation.KeyframeSet",
      "com.actionbarsherlock.internal.nineoldandroids.animation.FloatKeyframeSet",
      "com.actionbarsherlock.internal.nineoldandroids.animation.PropertyValuesHolder$FloatPropertyValuesHolder",
      "com.actionbarsherlock.internal.nineoldandroids.animation.Keyframe$ObjectKeyframe",
      "android.view.animation.AnticipateOvershootInterpolator",
      "android.content.ContentProvider",
      "android.content.SearchRecentSuggestionsProvider",
      "android.content.pm.Signature",
      "android.accounts.AccountAuthenticatorActivity",
      "android.graphics.Shader$TileMode",
      "com.actionbarsherlock.internal.nineoldandroids.animation.AnimatorSet$Dependency",
      "android.app.ListActivity",
      "android.view.animation.AnticipateInterpolator",
      "android.app.ExpandableListActivity",
      "android.widget.BaseAdapter",
      "android.widget.CursorAdapter",
      "android.widget.ResourceCursorAdapter",
      "android.widget.SimpleCursorAdapter",
      "android.app.NativeActivity",
      "android.content.res.Resources",
      "com.actionbarsherlock.internal.nineoldandroids.animation.PropertyValuesHolder$IntPropertyValuesHolder",
      "com.actionbarsherlock.internal.nineoldandroids.animation.Keyframe$IntKeyframe",
      "com.actionbarsherlock.internal.nineoldandroids.animation.IntKeyframeSet",
      "android.os.Parcel",
      "com.xtremelabs.robolectric.res.ResourceExtractor",
      "android.view.View",
      "android.view.ViewGroup",
      "com.actionbarsherlock.internal.nineoldandroids.view.NineViewGroup",
      "android.view.animation.DecelerateInterpolator",
      "com.actionbarsherlock.internal.widget.AbsActionBarView",
      "android.graphics.drawable.Drawable",
      "android.graphics.drawable.BitmapDrawable",
      "android.animation.IntEvaluator",
      "com.actionbarsherlock.app.ActionBar",
      "com.actionbarsherlock.internal.app.ActionBarImpl",
      "android.os.Handler",
      "com.xtremelabs.robolectric.tester.android.util.TestAttributeSet",
      "android.view.animation.LinearInterpolator",
      "com.actionbarsherlock.internal.nineoldandroids.animation.AnimatorSet$AnimatorSetListener",
      "android.util.DisplayMetrics",
      "android.view.animation.AccelerateInterpolator",
      "android.view.animation.BounceInterpolator",
      "android.content.res.Configuration",
      "android.view.animation.CycleInterpolator",
      "android.app.Fragment",
      "android.app.DialogFragment",
      "android.content.MutableContextWrapper",
      "android.database.AbstractCursor",
      "android.database.MatrixCursor"
    );
  }
}
