/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 05 22:44:53 GMT 2018
 */

package com.actionbarsherlock.app;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.actionbarsherlock.app.SherlockListFragment;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SherlockListFragment_ESTest extends SherlockListFragment_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SherlockListFragment sherlockListFragment0 = null;
      try {
        sherlockListFragment0 = new SherlockListFragment();
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Stub!
         //
         verifyException("android.os.Handler", e);
      }
  }
}
