/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Mon Nov 05 22:37:03 GMT 2018
 */

package com.actionbarsherlock.internal.nineoldandroids.widget;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class NineHorizontalScrollView_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.actionbarsherlock.internal.nineoldandroids.widget.NineHorizontalScrollView"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "Cp1252"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\Thiago\\AppData\\Local\\Temp\\"); 
    java.lang.System.setProperty("user.country", "US"); 
    java.lang.System.setProperty("user.dir", "C:\\Users\\Thiago\\Documents\\Calculadora\\Calculadora-de-Tributos-PJ\\ActionBarSherlock-Library"); 
    java.lang.System.setProperty("user.home", "C:\\Users\\Thiago"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "Thiago"); 
    java.lang.System.setProperty("user.timezone", "America/Sao_Paulo"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(NineHorizontalScrollView_ESTest_scaffolding.class.getClassLoader() ,
      "android.os.Bundle",
      "android.content.IntentSender$SendIntentException",
      "android.widget.FrameLayout",
      "android.net.Uri",
      "android.view.View$AccessibilityDelegate",
      "android.content.ComponentCallbacks",
      "android.view.MotionEvent$PointerProperties",
      "android.graphics.drawable.Drawable",
      "android.view.TouchDelegate",
      "org.xmlpull.v1.XmlSerializer",
      "android.widget.HorizontalScrollView",
      "android.database.sqlite.SQLiteDatabase",
      "android.animation.LayoutTransition",
      "android.os.Build$VERSION",
      "android.view.View$OnSystemUiVisibilityChangeListener",
      "android.os.Handler",
      "android.os.Looper",
      "android.graphics.Canvas",
      "android.view.accessibility.AccessibilityEvent",
      "android.net.Uri$Builder",
      "org.xmlpull.v1.XmlPullParser",
      "android.view.DragEvent",
      "android.view.animation.Interpolator",
      "android.content.res.Resources$NotFoundException",
      "android.content.IntentFilter",
      "android.view.View$OnGenericMotionListener",
      "android.view.KeyCharacterMap$KeyData",
      "android.graphics.Region",
      "android.view.View$OnLayoutChangeListener",
      "android.content.BroadcastReceiver$PendingResult",
      "android.content.IntentFilter$AuthorityEntry",
      "android.view.animation.LayoutAnimationController",
      "android.graphics.Paint",
      "android.view.View$OnAttachStateChangeListener",
      "android.view.accessibility.AccessibilityEventSource",
      "android.graphics.Path",
      "android.view.ViewParent",
      "android.animation.TimeInterpolator",
      "android.view.View$OnClickListener",
      "android.content.pm.PackageManager$NameNotFoundException",
      "android.content.IntentFilter$MalformedMimeTypeException",
      "android.os.Parcel",
      "android.content.IntentSender",
      "android.content.res.AssetManager",
      "android.view.InputDevice",
      "android.view.Menu",
      "android.content.ContextWrapper",
      "android.content.res.Resources$Theme",
      "android.os.Parcelable",
      "android.view.KeyEvent$Callback",
      "android.content.ComponentName",
      "android.view.ViewGroup$OnHierarchyChangeListener",
      "android.content.SharedPreferences",
      "android.view.ViewGroup$MarginLayoutParams",
      "android.content.res.Configuration",
      "android.view.animation.Transformation",
      "com.actionbarsherlock.internal.nineoldandroids.view.animation.AnimatorProxy",
      "android.util.Printer",
      "android.view.View$OnCreateContextMenuListener",
      "android.graphics.Rect",
      "android.graphics.Region$Op",
      "android.view.ActionMode",
      "android.content.pm.PackageManager",
      "android.graphics.drawable.Drawable$Callback",
      "android.widget.RemoteViews$RemoteView",
      "android.os.IBinder",
      "android.view.KeyEvent$DispatcherState",
      "android.util.AttributeSet",
      "android.content.ContentResolver",
      "android.view.View",
      "android.database.DatabaseErrorHandler",
      "android.content.ServiceConnection",
      "android.view.animation.Animation",
      "android.graphics.Matrix",
      "android.view.View$OnLongClickListener",
      "android.graphics.RectF",
      "android.os.Build$VERSION_CODES",
      "android.view.ViewGroup$LayoutParams",
      "android.util.AndroidException",
      "android.view.InputEvent",
      "android.text.InputType",
      "android.content.BroadcastReceiver",
      "android.view.animation.Animation$AnimationListener",
      "android.view.ViewGroup",
      "org.xmlpull.v1.XmlPullParserException",
      "android.util.SparseArray",
      "android.os.PatternMatcher",
      "android.view.accessibility.AccessibilityRecord",
      "android.view.ViewPropertyAnimator",
      "com.actionbarsherlock.internal.nineoldandroids.widget.NineHorizontalScrollView",
      "android.content.pm.ApplicationInfo",
      "android.view.inputmethod.EditorInfo",
      "android.content.Context",
      "android.view.ContextMenu",
      "android.view.accessibility.AccessibilityNodeInfo",
      "android.view.KeyEvent",
      "android.view.inputmethod.InputConnection",
      "android.content.Intent",
      "android.content.res.TypedArray",
      "android.view.ActionMode$Callback",
      "android.content.ClipData",
      "android.view.MotionEvent",
      "android.os.Build",
      "android.widget.FrameLayout$LayoutParams",
      "android.view.View$OnKeyListener",
      "android.view.MotionEvent$PointerCoords",
      "android.graphics.Point",
      "android.content.pm.PackageItemInfo",
      "android.database.sqlite.SQLiteDatabase$CursorFactory",
      "android.view.View$DragShadowBuilder",
      "android.graphics.Bitmap",
      "android.view.KeyCharacterMap",
      "android.view.View$OnFocusChangeListener",
      "android.view.ViewTreeObserver",
      "android.content.ClipDescription",
      "android.database.sqlite.SQLiteClosable",
      "android.view.View$OnTouchListener",
      "android.view.View$OnHoverListener",
      "android.view.ContextMenu$ContextMenuInfo",
      "android.view.ViewManager",
      "android.content.res.Resources",
      "android.view.View$OnDragListener"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(NineHorizontalScrollView_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "android.view.View",
      "android.view.ViewGroup",
      "android.widget.FrameLayout",
      "android.widget.HorizontalScrollView",
      "com.actionbarsherlock.internal.nineoldandroids.widget.NineHorizontalScrollView",
      "android.os.Build$VERSION",
      "android.view.animation.Animation",
      "com.actionbarsherlock.internal.nineoldandroids.view.animation.AnimatorProxy",
      "android.content.Context",
      "android.content.ContextWrapper",
      "android.graphics.Rect",
      "android.content.BroadcastReceiver",
      "android.content.IntentFilter",
      "android.net.Uri",
      "android.view.DragEvent",
      "android.view.InputEvent",
      "android.view.MotionEvent",
      "android.view.accessibility.AccessibilityRecord",
      "android.view.accessibility.AccessibilityEvent",
      "android.view.KeyEvent",
      "android.graphics.Region",
      "android.os.Bundle"
    );
  }
}
