/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 05 21:56:34 GMT 2018
 */

package com.actionbarsherlock;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import android.app.Activity;
import android.content.Context;
import android.content.res.Configuration;
import android.view.KeyEvent;
import android.view.MenuItem;
import android.view.View;
import com.actionbarsherlock.ActionBarSherlock;
import com.actionbarsherlock.internal.ActionBarSherlockCompat;
import com.actionbarsherlock.internal.ActionBarSherlockNative;
import com.actionbarsherlock.view.ActionMode;
import com.xtremelabs.robolectric.tester.android.view.TestMenu;
import com.xtremelabs.robolectric.tester.android.view.TestMenuItem;
import com.xtremelabs.robolectric.tester.android.view.TestSubMenu;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ActionBarSherlock_ESTest extends ActionBarSherlock_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ActionBarSherlockNative actionBarSherlockNative0 = new ActionBarSherlockNative((Activity) null, 174);
      TestSubMenu testSubMenu0 = new TestSubMenu();
      boolean boolean0 = actionBarSherlockNative0.dispatchPrepareOptionsMenu(testSubMenu0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ActionBarSherlockNative actionBarSherlockNative0 = new ActionBarSherlockNative((Activity) null, 776);
      TestMenu testMenu0 = new TestMenu();
      boolean boolean0 = actionBarSherlockNative0.dispatchCreateOptionsMenu(testMenu0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ActionBarSherlockCompat actionBarSherlockCompat0 = new ActionBarSherlockCompat((Activity) null, 14);
      actionBarSherlockCompat0.setProgressBarVisibility(true);
      assertEquals(1, ActionBarSherlock.FLAG_DELEGATE);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ActionBarSherlockCompat actionBarSherlockCompat0 = new ActionBarSherlockCompat((Activity) null, 3399);
      actionBarSherlockCompat0.setProgressBarIndeterminateVisibility(false);
      assertEquals(1, ActionBarSherlock.FLAG_DELEGATE);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ActionBarSherlockCompat actionBarSherlockCompat0 = new ActionBarSherlockCompat((Activity) null, (-3393));
      actionBarSherlockCompat0.dispatchInvalidateOptionsMenu();
      assertEquals(1, ActionBarSherlock.FLAG_DELEGATE);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ActionBarSherlockCompat actionBarSherlockCompat0 = new ActionBarSherlockCompat((Activity) null, 0);
      actionBarSherlockCompat0.setUiOptions(0, 0);
      assertEquals(1, ActionBarSherlock.FLAG_DELEGATE);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ActionBarSherlockCompat actionBarSherlockCompat0 = new ActionBarSherlockCompat((Activity) null, 1);
      actionBarSherlockCompat0.setUiOptions(1);
      assertEquals(1, ActionBarSherlock.FLAG_DELEGATE);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ActionBarSherlockCompat actionBarSherlockCompat0 = new ActionBarSherlockCompat((Activity) null, (-474));
      actionBarSherlockCompat0.setSecondaryProgress(1207);
      assertEquals(1, ActionBarSherlock.FLAG_DELEGATE);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ActionBarSherlockCompat actionBarSherlockCompat0 = new ActionBarSherlockCompat((Activity) null, 213);
      actionBarSherlockCompat0.setProgressBarIndeterminate(true);
      assertEquals(1, ActionBarSherlock.FLAG_DELEGATE);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ActionBarSherlockCompat actionBarSherlockCompat0 = new ActionBarSherlockCompat((Activity) null, 0);
      actionBarSherlockCompat0.setProgress((-2503));
      assertEquals(1, ActionBarSherlock.FLAG_DELEGATE);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ActionBarSherlockCompat actionBarSherlockCompat0 = new ActionBarSherlockCompat((Activity) null, (-3393));
      boolean boolean0 = actionBarSherlockCompat0.requestFeature(0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ActionBarSherlockCompat actionBarSherlockCompat0 = new ActionBarSherlockCompat((Activity) null, (-474));
      boolean boolean0 = actionBarSherlockCompat0.hasFeature(1207);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      ActionBarSherlockNative actionBarSherlockNative0 = new ActionBarSherlockNative((Activity) null, 779);
      TestMenu testMenu0 = new TestMenu();
      boolean boolean0 = actionBarSherlockNative0.dispatchPrepareOptionsMenu(testMenu0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      ActionBarSherlockCompat actionBarSherlockCompat0 = new ActionBarSherlockCompat((Activity) null, 0);
      TestSubMenu testSubMenu0 = new TestSubMenu();
      boolean boolean0 = actionBarSherlockCompat0.dispatchMenuOpened(0, testSubMenu0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      ActionBarSherlockNative actionBarSherlockNative0 = new ActionBarSherlockNative((Activity) null, 1);
      ActionMode.Callback actionMode_Callback0 = mock(ActionMode.Callback.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        actionBarSherlockNative0.startActionMode(actionMode_Callback0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.actionbarsherlock.internal.ActionBarSherlockNative", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      ActionBarSherlockNative actionBarSherlockNative0 = new ActionBarSherlockNative((Activity) null, 1);
      // Undeclared exception!
      try { 
        actionBarSherlockNative0.setProgressBarVisibility(true);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.actionbarsherlock.internal.ActionBarSherlockNative", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      ActionBarSherlockNative actionBarSherlockNative0 = new ActionBarSherlockNative((Activity) null, (-3922));
      // Undeclared exception!
      try { 
        actionBarSherlockNative0.setProgressBarIndeterminateVisibility(false);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.actionbarsherlock.internal.ActionBarSherlockNative", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      ActionBarSherlockCompat actionBarSherlockCompat0 = new ActionBarSherlockCompat((Activity) null, 196);
      // Undeclared exception!
      try { 
        actionBarSherlockCompat0.setContentView(196);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.actionbarsherlock.internal.ActionBarSherlockCompat", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      ActionBarSherlockNative actionBarSherlockNative0 = new ActionBarSherlockNative((Activity) null, 213);
      // Undeclared exception!
      try { 
        actionBarSherlockNative0.requestFeature(1499);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.actionbarsherlock.internal.ActionBarSherlockNative", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      // Undeclared exception!
      try { 
        ActionBarSherlock.registerImplementation((Class<? extends ActionBarSherlock>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.actionbarsherlock.ActionBarSherlock", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      ActionBarSherlockNative actionBarSherlockNative0 = new ActionBarSherlockNative((Activity) null, 779);
      // Undeclared exception!
      try { 
        actionBarSherlockNative0.hasFeature(1203);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.actionbarsherlock.internal.ActionBarSherlockNative", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      ActionBarSherlockNative actionBarSherlockNative0 = new ActionBarSherlockNative((Activity) null, 213);
      // Undeclared exception!
      try { 
        actionBarSherlockNative0.getActionBar();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.actionbarsherlock.internal.ActionBarSherlockNative", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      ActionBarSherlockCompat actionBarSherlockCompat0 = new ActionBarSherlockCompat((Activity) null, (-1390));
      TestMenu testMenu0 = new TestMenu((Context) null);
      // Undeclared exception!
      try { 
        actionBarSherlockCompat0.dispatchPrepareOptionsMenu(testMenu0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.actionbarsherlock.internal.view.menu.MenuBuilder", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      ActionBarSherlockNative actionBarSherlockNative0 = new ActionBarSherlockNative((Activity) null, (-653));
      // Undeclared exception!
      try { 
        actionBarSherlockNative0.dispatchOptionsItemSelected((MenuItem) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.actionbarsherlock.internal.ActionBarSherlockNative", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      ActionBarSherlockCompat actionBarSherlockCompat0 = new ActionBarSherlockCompat((Activity) null, 47);
      TestMenuItem testMenuItem0 = new TestMenuItem();
      // Undeclared exception!
      try { 
        actionBarSherlockCompat0.dispatchOptionsItemSelected(testMenuItem0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Native callback invoked. Create a test case and report!
         //
         verifyException("com.actionbarsherlock.internal.ActionBarSherlockCompat", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      ActionBarSherlockCompat actionBarSherlockCompat0 = new ActionBarSherlockCompat((Activity) null, 190);
      // Undeclared exception!
      try { 
        actionBarSherlockCompat0.dispatchOpenOptionsMenu();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.actionbarsherlock.internal.view.menu.ActionMenuPresenter", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      ActionBarSherlockCompat actionBarSherlockCompat0 = new ActionBarSherlockCompat((Activity) null, 2292);
      // Undeclared exception!
      try { 
        actionBarSherlockCompat0.dispatchKeyEvent((KeyEvent) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.actionbarsherlock.internal.ActionBarSherlockCompat", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      ActionBarSherlockNative actionBarSherlockNative0 = new ActionBarSherlockNative((Activity) null, 0);
      // Undeclared exception!
      try { 
        actionBarSherlockNative0.dispatchInvalidateOptionsMenu();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.actionbarsherlock.internal.ActionBarSherlockNative", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      ActionBarSherlockCompat actionBarSherlockCompat0 = new ActionBarSherlockCompat((Activity) null, (-3824));
      // Undeclared exception!
      try { 
        actionBarSherlockCompat0.dispatchCloseOptionsMenu();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.actionbarsherlock.internal.view.menu.ActionMenuPresenter", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      // Undeclared exception!
      try { 
        ActionBarSherlock.wrap((Activity) null, 1);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // No implementations match configuration.
         //
         verifyException("com.actionbarsherlock.ActionBarSherlock", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      ActionBarSherlockNative actionBarSherlockNative0 = new ActionBarSherlockNative((Activity) null, (-653));
      // Undeclared exception!
      try { 
        actionBarSherlockNative0.getMenuInflater();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.actionbarsherlock.internal.ActionBarSherlockNative", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Class<ActionBarSherlockNative> class0 = ActionBarSherlockNative.class;
      ActionBarSherlock.registerImplementation(class0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Class<ActionBarSherlock> class0 = ActionBarSherlock.class;
      // Undeclared exception!
      try { 
        ActionBarSherlock.registerImplementation(class0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Class ActionBarSherlock is not annotated with @Implementation
         //
         verifyException("com.actionbarsherlock.ActionBarSherlock", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Class<ActionBarSherlockCompat> class0 = ActionBarSherlockCompat.class;
      ActionBarSherlock.registerImplementation(class0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      ActionBarSherlockNative actionBarSherlockNative0 = new ActionBarSherlockNative((Activity) null, 40);
      // Undeclared exception!
      try { 
        actionBarSherlockNative0.setTitle(40);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.actionbarsherlock.ActionBarSherlock", e);
      }
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      ActionBarSherlockNative actionBarSherlockNative0 = new ActionBarSherlockNative((Activity) null, 213);
      actionBarSherlockNative0.dispatchTitleChanged((CharSequence) null, 213);
      assertEquals(1, ActionBarSherlock.FLAG_DELEGATE);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      ActionBarSherlockNative actionBarSherlockNative0 = new ActionBarSherlockNative((Activity) null, 779);
      boolean boolean0 = actionBarSherlockNative0.dispatchCloseOptionsMenu();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      // Undeclared exception!
      try { 
        ActionBarSherlock.wrap((Activity) null);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // No implementations match configuration.
         //
         verifyException("com.actionbarsherlock.ActionBarSherlock", e);
      }
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      ActionBarSherlockNative actionBarSherlockNative0 = new ActionBarSherlockNative((Activity) null, 779);
      actionBarSherlockNative0.dispatchPause();
      assertEquals(1, ActionBarSherlock.FLAG_DELEGATE);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      ActionBarSherlockNative actionBarSherlockNative0 = new ActionBarSherlockNative((Activity) null, (-653));
      actionBarSherlockNative0.dispatchPostResume();
      assertEquals(1, ActionBarSherlock.FLAG_DELEGATE);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      ActionBarSherlockNative actionBarSherlockNative0 = new ActionBarSherlockNative((Activity) null, (-621));
      boolean boolean0 = actionBarSherlockNative0.dispatchOpenOptionsMenu();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      ActionBarSherlockNative actionBarSherlockNative0 = new ActionBarSherlockNative((Activity) null, (-3922));
      actionBarSherlockNative0.dispatchConfigurationChanged((Configuration) null);
      assertEquals(1, ActionBarSherlock.FLAG_DELEGATE);
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      ActionBarSherlockNative actionBarSherlockNative0 = new ActionBarSherlockNative((Activity) null, 213);
      // Undeclared exception!
      try { 
        actionBarSherlockNative0.setContentView((View) null);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Stub!
         //
         verifyException("android.view.ViewGroup$LayoutParams", e);
      }
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      ActionBarSherlockNative actionBarSherlockNative0 = new ActionBarSherlockNative((Activity) null, 779);
      TestMenu testMenu0 = new TestMenu();
      actionBarSherlockNative0.dispatchPanelClosed((-1), testMenu0);
      assertEquals(1, ActionBarSherlock.FLAG_DELEGATE);
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      ActionBarSherlockNative actionBarSherlockNative0 = new ActionBarSherlockNative((Activity) null, (-3922));
      TestSubMenu testSubMenu0 = new TestSubMenu();
      boolean boolean0 = actionBarSherlockNative0.dispatchMenuOpened((-3393), testSubMenu0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      ActionBarSherlockNative actionBarSherlockNative0 = new ActionBarSherlockNative((Activity) null, 1);
      actionBarSherlockNative0.dispatchDestroy();
      assertEquals(1, ActionBarSherlock.FLAG_DELEGATE);
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      ActionBarSherlockNative actionBarSherlockNative0 = new ActionBarSherlockNative((Activity) null, (-3922));
      boolean boolean0 = actionBarSherlockNative0.dispatchKeyEvent((KeyEvent) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      ActionBarSherlockNative actionBarSherlockNative0 = new ActionBarSherlockNative((Activity) null, 779);
      actionBarSherlockNative0.dispatchStop();
      assertEquals(1, ActionBarSherlock.FLAG_DELEGATE);
  }
}
