/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Mon Nov 05 22:23:57 GMT 2018
 */

package com.actionbarsherlock.app;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class SherlockFragmentActivity_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.actionbarsherlock.app.SherlockFragmentActivity"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "Cp1252"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\Thiago\\AppData\\Local\\Temp\\"); 
    java.lang.System.setProperty("user.country", "US"); 
    java.lang.System.setProperty("user.dir", "C:\\Users\\Thiago\\Documents\\Calculadora\\Calculadora-de-Tributos-PJ\\ActionBarSherlock-Library"); 
    java.lang.System.setProperty("user.home", "C:\\Users\\Thiago"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "Thiago"); 
    java.lang.System.setProperty("user.timezone", "America/Sao_Paulo"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(SherlockFragmentActivity_ESTest_scaffolding.class.getClassLoader() ,
      "android.os.Bundle",
      "android.view.View$AccessibilityDelegate",
      "android.content.ComponentCallbacks",
      "android.view.MotionEvent$PointerProperties",
      "android.view.TouchDelegate",
      "org.xmlpull.v1.XmlSerializer",
      "android.view.MenuItem$OnActionExpandListener",
      "android.graphics.Bitmap$Config",
      "android.graphics.Paint$Align",
      "android.support.v4.app._ActionBarSherlockTrojanHorse",
      "android.content.res.ColorStateList",
      "android.support.v4.app.BackStackRecord$Op",
      "android.database.sqlite.SQLiteDatabase",
      "android.widget.HorizontalScrollView",
      "android.animation.LayoutTransition",
      "android.view.View$OnSystemUiVisibilityChangeListener",
      "android.os.Handler",
      "android.view.inputmethod.ExtractedTextRequest",
      "android.graphics.Shader",
      "android.view.Display",
      "android.support.v4.app.LoaderManagerImpl",
      "org.xmlpull.v1.XmlPullParser",
      "com.actionbarsherlock.ActionBarSherlock$OnPreparePanelListener",
      "android.database.CharArrayBuffer",
      "android.view.DragEvent",
      "android.accounts.Account",
      "com.xtremelabs.robolectric.tester.android.view.TestMenuItem",
      "android.content.IntentFilter",
      "android.support.v4.app.Fragment",
      "android.app.PendingIntent$CanceledException",
      "android.view.View$OnGenericMotionListener",
      "android.view.SubMenu",
      "android.content.IntentFilter$AuthorityEntry",
      "android.content.pm.FeatureInfo",
      "android.graphics.Canvas$EdgeType",
      "android.view.InflateException",
      "com.actionbarsherlock.internal.view.menu.MenuBuilder",
      "android.graphics.Matrix$ScaleToFit",
      "com.actionbarsherlock.internal.app.ActionBarImpl",
      "android.graphics.Paint",
      "android.view.View$OnAttachStateChangeListener",
      "android.view.animation.AlphaAnimation",
      "android.widget.AbsListView$LayoutParams",
      "android.content.DialogInterface$OnShowListener",
      "android.app.FragmentManager",
      "android.graphics.Path",
      "android.graphics.Paint$Join",
      "android.view.View$OnClickListener",
      "android.content.IntentSender$OnFinished",
      "android.content.pm.PackageManager$NameNotFoundException",
      "com.actionbarsherlock.app.ActionBar",
      "com.actionbarsherlock.app.ActionBar$LayoutParams",
      "android.os.RemoteException",
      "android.content.IntentFilter$MalformedMimeTypeException",
      "android.database.sqlite.SQLiteTransactionListener",
      "com.actionbarsherlock.internal.app.ActionBarImpl$TabImpl",
      "android.view.inputmethod.CorrectionInfo",
      "android.view.InputDevice",
      "android.view.MenuInflater",
      "android.view.Menu",
      "android.view.ViewTreeObserver$OnPreDrawListener",
      "android.widget.LinearLayout$LayoutParams",
      "android.graphics.Bitmap$CompressFormat",
      "android.app.ActionBar$OnMenuVisibilityListener",
      "android.content.ContextWrapper",
      "android.content.res.Resources$Theme",
      "android.graphics.ColorFilter",
      "com.actionbarsherlock.ActionBarSherlock$OnActionModeStartedListener",
      "android.os.Parcelable",
      "android.content.ComponentName",
      "com.actionbarsherlock.internal.widget.IcsAdapterView$OnItemSelectedListener",
      "android.app.ActionBar$OnNavigationListener",
      "android.content.SyncInfo",
      "android.graphics.PorterDuff$Mode",
      "android.view.Window$Callback",
      "android.support.v4.app.FragmentManager",
      "android.content.SharedPreferences",
      "com.actionbarsherlock.view.ActionMode",
      "android.view.animation.Transformation",
      "android.animation.Animator$AnimatorListener",
      "android.util.Printer",
      "android.view.View$OnCreateContextMenuListener",
      "com.actionbarsherlock.internal.nineoldandroids.animation.AnimatorSet",
      "android.view.animation.ScaleAnimation",
      "android.view.inputmethod.CompletionInfo",
      "android.graphics.Rect",
      "android.graphics.Region$Op",
      "android.os.IBinder$DeathRecipient",
      "android.view.ActionMode",
      "android.widget.LinearLayout",
      "android.content.pm.PackageManager",
      "android.graphics.drawable.Drawable$Callback",
      "android.view.WindowManager",
      "com.actionbarsherlock.ActionBarSherlock$Implementation",
      "android.animation.Animator",
      "android.support.v4.app.LoaderManager$LoaderCallbacks",
      "android.content.pm.ProviderInfo",
      "android.util.AndroidRuntimeException",
      "com.actionbarsherlock.view.MenuItem",
      "android.view.animation.AccelerateDecelerateInterpolator",
      "android.content.ContentResolver",
      "android.content.pm.ActivityInfo",
      "android.database.DatabaseErrorHandler",
      "android.content.pm.InstrumentationInfo",
      "android.graphics.Canvas$VertexMode",
      "android.content.DialogInterface$OnDismissListener",
      "android.database.DataSetObserver",
      "com.actionbarsherlock.app.SherlockFragmentActivity",
      "android.view.View$OnLongClickListener",
      "android.graphics.RectF",
      "android.content.pm.PermissionGroupInfo",
      "android.util.AndroidException",
      "android.view.InputEvent",
      "com.actionbarsherlock.internal.view.menu.SubMenuBuilder",
      "android.content.pm.ComponentInfo",
      "android.support.v4.content.Loader$OnLoadCompleteListener",
      "android.app.PendingIntent$OnFinished",
      "android.util.DisplayMetrics",
      "org.xmlpull.v1.XmlPullParserException",
      "com.actionbarsherlock.internal.nineoldandroids.view.NineViewGroup",
      "com.actionbarsherlock.view.MenuItem$OnActionExpandListener",
      "android.view.LayoutInflater$Filter",
      "android.app.Application",
      "android.support.v4.app.FragmentManager$OnBackStackChangedListener",
      "com.actionbarsherlock.internal.widget.ScrollingTabContainerView$TabView",
      "android.content.DialogInterface$OnCancelListener",
      "android.view.accessibility.AccessibilityRecord",
      "android.content.Loader",
      "com.actionbarsherlock.internal.widget.IcsAbsSpinner",
      "com.actionbarsherlock.internal.view.menu.MenuView",
      "android.content.ContentValues",
      "android.view.LayoutInflater$Factory2",
      "com.actionbarsherlock.internal.nineoldandroids.widget.NineHorizontalScrollView",
      "com.actionbarsherlock.internal.nineoldandroids.animation.AnimatorSet$Builder",
      "android.view.Window",
      "android.view.inputmethod.EditorInfo",
      "com.actionbarsherlock.internal.ActionBarSherlockNative",
      "android.content.SharedPreferences$Editor",
      "android.content.res.AssetFileDescriptor",
      "com.actionbarsherlock.view.MenuItem$OnMenuItemClickListener",
      "android.support.v4.app.Fragment$SavedState$1",
      "android.app.LoaderManager$LoaderCallbacks",
      "com.actionbarsherlock.internal.view.menu.MenuPresenter",
      "com.actionbarsherlock.app.ActionBar$TabListener",
      "android.os.Parcelable$Creator",
      "android.content.pm.PackageInfo",
      "android.view.MenuItem",
      "android.view.SurfaceHolder$Callback",
      "com.actionbarsherlock.internal.view.menu.MenuBuilder$ItemInvoker",
      "android.os.Build",
      "android.widget.FrameLayout$LayoutParams",
      "android.view.WindowManager$LayoutParams",
      "com.actionbarsherlock.internal.nineoldandroids.animation.ValueAnimator$5",
      "com.actionbarsherlock.internal.nineoldandroids.animation.ValueAnimator$3",
      "android.graphics.MaskFilter",
      "com.actionbarsherlock.internal.nineoldandroids.animation.ValueAnimator$4",
      "android.view.MotionEvent$PointerCoords",
      "android.view.LayoutInflater",
      "android.support.v4.app.Fragment$InstantiationException",
      "android.support.v4.util.LogWriter",
      "android.view.InputQueue$Callback",
      "android.view.animation.LayoutAnimationController$AnimationParameters",
      "android.view.InputDevice$MotionRange",
      "android.view.inputmethod.ExtractedText",
      "com.actionbarsherlock.internal.nineoldandroids.animation.ValueAnimator$1",
      "com.actionbarsherlock.view.ActionMode$Callback",
      "com.actionbarsherlock.internal.nineoldandroids.animation.ValueAnimator$2",
      "android.content.pm.PackageItemInfo",
      "android.database.sqlite.SQLiteDatabase$CursorFactory",
      "android.graphics.Bitmap",
      "android.view.KeyCharacterMap",
      "android.view.ViewTreeObserver",
      "android.content.ClipDescription",
      "android.content.pm.ServiceInfo",
      "android.app.Activity",
      "android.support.v4.app.FragmentTransaction",
      "android.view.View$OnHoverListener",
      "android.view.ViewManager",
      "android.content.res.Resources",
      "android.view.View$OnDragListener",
      "android.content.DialogInterface$OnClickListener",
      "android.content.pm.PermissionInfo",
      "android.os.ParcelFileDescriptor",
      "android.content.IntentSender$SendIntentException",
      "android.net.Uri",
      "android.widget.FrameLayout",
      "android.view.ViewTreeObserver$OnScrollChangedListener",
      "android.graphics.Rasterizer",
      "android.graphics.drawable.Drawable",
      "android.database.sqlite.SQLiteCursorDriver",
      "com.actionbarsherlock.app.ActionBar$OnNavigationListener",
      "com.actionbarsherlock.view.MenuInflater",
      "android.graphics.drawable.Drawable$ConstantState",
      "android.os.Build$VERSION",
      "com.actionbarsherlock.view.SubMenu",
      "com.actionbarsherlock.internal.ActionBarSherlockCompat",
      "android.os.Looper",
      "android.content.SyncStatusObserver",
      "android.graphics.Canvas",
      "android.view.accessibility.AccessibilityEvent",
      "android.net.Uri$Builder",
      "android.app.FragmentManager$BackStackEntry",
      "android.view.animation.Interpolator",
      "android.content.res.Resources$NotFoundException",
      "com.actionbarsherlock.internal.widget.ActionBarContainer",
      "android.view.KeyCharacterMap$KeyData",
      "com.actionbarsherlock.internal.app.ActionBarImpl$ActionModeImpl",
      "android.graphics.Region",
      "android.view.ActionProvider",
      "android.view.ViewTreeObserver$OnGlobalLayoutListener",
      "android.view.View$OnLayoutChangeListener",
      "android.graphics.Paint$Cap",
      "android.content.BroadcastReceiver$PendingResult",
      "android.os.Message",
      "android.view.animation.LayoutAnimationController",
      "com.actionbarsherlock.internal.widget.ScrollingTabContainerView",
      "android.graphics.Xfermode",
      "android.view.accessibility.AccessibilityEventSource",
      "com.actionbarsherlock.internal.widget.ActionBarContextView",
      "android.animation.LayoutTransition$TransitionListener",
      "android.view.ViewParent",
      "android.animation.TimeInterpolator",
      "android.support.v4.app.Fragment$SavedState",
      "com.actionbarsherlock.app.ActionBar$Tab",
      "android.database.sqlite.SQLiteProgram",
      "android.graphics.PathEffect",
      "android.app.Dialog",
      "android.app.FragmentTransaction",
      "android.os.Parcel",
      "com.actionbarsherlock.internal.widget.IcsSpinner",
      "android.app.FragmentManager$OnBackStackChangedListener",
      "android.graphics.Movie",
      "android.content.IntentSender",
      "android.content.res.AssetManager",
      "android.view.ViewTreeObserver$OnGlobalFocusChangeListener",
      "android.app.Fragment",
      "android.widget.SpinnerAdapter",
      "android.view.KeyEvent$Callback",
      "android.view.ViewGroup$OnHierarchyChangeListener",
      "android.content.OperationApplicationException",
      "android.content.ComponentCallbacks2",
      "android.util.SparseBooleanArray",
      "android.util.TypedValue",
      "android.content.res.Configuration",
      "android.view.ViewGroup$MarginLayoutParams",
      "com.actionbarsherlock.ActionBarSherlock",
      "com.actionbarsherlock.internal.nineoldandroids.widget.NineLinearLayout",
      "com.actionbarsherlock.internal.nineoldandroids.view.animation.AnimatorProxy",
      "android.app.Application$ActivityLifecycleCallbacks",
      "com.actionbarsherlock.internal.nineoldandroids.animation.Animator$AnimatorListener",
      "com.actionbarsherlock.ActionBarSherlock$OnMenuItemSelectedListener",
      "android.widget.RemoteViews$RemoteView",
      "android.content.res.XmlResourceParser",
      "android.app.PendingIntent",
      "android.view.KeyEvent$DispatcherState",
      "android.os.IBinder",
      "com.actionbarsherlock.internal.nineoldandroids.animation.Animator",
      "android.util.AttributeSet",
      "com.actionbarsherlock.internal.nineoldandroids.animation.ObjectAnimator",
      "com.actionbarsherlock.internal.nineoldandroids.widget.NineFrameLayout",
      "android.graphics.Paint$FontMetrics",
      "android.view.animation.AnimationSet",
      "android.view.ContextThemeWrapper",
      "android.view.View",
      "android.content.ServiceConnection",
      "android.view.ViewTreeObserver$OnTouchModeChangeListener",
      "android.view.animation.Animation",
      "com.actionbarsherlock.internal.nineoldandroids.animation.ValueAnimator",
      "android.graphics.Matrix",
      "android.app.ActionBar$LayoutParams",
      "android.support.v4.app.LoaderManager",
      "android.database.sqlite.SQLiteQuery",
      "android.content.ContentProviderResult",
      "android.app.ActionBar$Tab",
      "android.os.Build$VERSION_CODES",
      "android.view.MenuItem$OnMenuItemClickListener",
      "android.content.SharedPreferences$OnSharedPreferenceChangeListener",
      "android.content.DialogInterface$OnKeyListener",
      "android.view.ViewGroup$LayoutParams",
      "android.text.InputType",
      "android.content.ClipData$Item",
      "com.actionbarsherlock.internal.widget.AbsActionBarView",
      "android.view.animation.Animation$AnimationListener",
      "android.content.BroadcastReceiver",
      "android.view.ViewGroup",
      "android.database.ContentObserver",
      "android.util.SparseArray",
      "android.os.MessageQueue",
      "android.os.PatternMatcher",
      "android.support.v4.app.FragmentActivity",
      "android.graphics.DrawFilter",
      "android.support.v4.app.FragmentManager$BackStackEntry",
      "android.content.ContentProviderClient",
      "android.view.ViewPropertyAnimator",
      "android.support.v4.app.FragmentManagerImpl",
      "android.content.pm.ApplicationInfo",
      "android.view.animation.DecelerateInterpolator",
      "android.graphics.BitmapFactory$Options",
      "android.graphics.Typeface",
      "android.content.Context",
      "android.view.ContextMenu",
      "android.view.accessibility.AccessibilityNodeInfo",
      "android.view.KeyEvent",
      "android.widget.Adapter",
      "com.actionbarsherlock.internal.widget.IcsAdapterView",
      "android.support.v4.app.SuperNotCalledException",
      "android.view.LayoutInflater$Factory",
      "android.view.inputmethod.InputConnection",
      "com.actionbarsherlock.view.ActionProvider",
      "android.content.SyncAdapterType",
      "android.content.Intent",
      "android.graphics.Paint$FontMetricsInt",
      "com.actionbarsherlock.internal.view.menu.MenuPresenter$Callback",
      "com.actionbarsherlock.view.Menu",
      "com.actionbarsherlock.view.Window$Callback",
      "com.xtremelabs.robolectric.tester.android.view.TestSubMenu",
      "android.content.res.TypedArray",
      "android.view.ActionMode$Callback",
      "com.actionbarsherlock.internal.widget.ActionBarView",
      "android.content.ClipData",
      "android.graphics.Paint$Style",
      "android.view.MotionEvent",
      "com.actionbarsherlock.internal.view.menu.ActionMenuView",
      "android.support.v4.app.LoaderManagerImpl$LoaderInfo",
      "android.database.sqlite.SQLiteStatement",
      "com.actionbarsherlock.internal.view.menu.MenuBuilder$Callback",
      "android.app.LoaderManager",
      "android.database.Cursor",
      "android.content.DialogInterface",
      "android.app.Fragment$SavedState",
      "android.app.ActionBar",
      "android.support.v4.content.Loader",
      "android.view.View$OnKeyListener",
      "android.os.IInterface",
      "android.support.v4.app.BackStackRecord",
      "android.graphics.Point",
      "android.support.v4.app.FragmentActivity$1",
      "com.xtremelabs.robolectric.tester.android.view.TestMenu",
      "android.database.SQLException",
      "android.content.pm.ResolveInfo",
      "android.view.View$DragShadowBuilder",
      "android.graphics.Picture",
      "com.actionbarsherlock.internal.view.menu.MenuWrapper",
      "com.actionbarsherlock.internal.widget.IcsLinearLayout",
      "android.view.View$OnFocusChangeListener",
      "com.actionbarsherlock.ActionBarSherlock$OnActionModeFinishedListener",
      "com.actionbarsherlock.ActionBarSherlock$OnCreatePanelMenuListener",
      "android.database.sqlite.SQLiteClosable",
      "com.actionbarsherlock.app.ActionBar$OnMenuVisibilityListener",
      "android.view.View$OnTouchListener",
      "android.view.ContextMenu$ContextMenuInfo",
      "android.view.SurfaceHolder$Callback2"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(SherlockFragmentActivity_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "android.content.Context",
      "android.content.ContextWrapper",
      "android.view.ContextThemeWrapper",
      "android.app.Activity",
      "android.support.v4.app.FragmentActivity",
      "android.support.v4.app._ActionBarSherlockTrojanHorse",
      "com.actionbarsherlock.app.SherlockFragmentActivity",
      "com.actionbarsherlock.ActionBarSherlock",
      "android.os.Build$VERSION",
      "android.view.InputEvent",
      "android.view.KeyEvent",
      "android.view.View",
      "android.view.ViewGroup",
      "android.support.v4.app.Fragment",
      "android.content.IntentFilter",
      "android.content.res.Configuration",
      "com.actionbarsherlock.app.ActionBar",
      "com.actionbarsherlock.internal.app.ActionBarImpl",
      "android.os.Handler",
      "android.net.Uri",
      "android.os.Bundle",
      "android.content.BroadcastReceiver",
      "com.actionbarsherlock.internal.view.menu.MenuWrapper",
      "com.xtremelabs.robolectric.tester.android.view.TestMenu",
      "com.xtremelabs.robolectric.tester.android.view.TestSubMenu"
    );
  }
}
