/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 05 22:15:04 GMT 2018
 */

package com.actionbarsherlock.internal.nineoldandroids.view.animation;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import android.view.View;
import com.actionbarsherlock.internal.nineoldandroids.view.animation.AnimatorProxy;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AnimatorProxy_ESTest extends AnimatorProxy_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try { 
        AnimatorProxy.wrap((View) null);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Stub!
         //
         verifyException("android.view.animation.Animation", e);
      }
  }
}
