/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Mon Nov 05 22:42:56 GMT 2018
 */

package com.actionbarsherlock.internal.widget;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class CapitalizingButton_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.actionbarsherlock.internal.widget.CapitalizingButton"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {} 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "Cp1252"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\Thiago\\AppData\\Local\\Temp\\"); 
    java.lang.System.setProperty("user.country", "US"); 
    java.lang.System.setProperty("user.dir", "C:\\Users\\Thiago\\Documents\\Calculadora\\Calculadora-de-Tributos-PJ\\ActionBarSherlock-Library"); 
    java.lang.System.setProperty("user.home", "C:\\Users\\Thiago"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "Thiago"); 
    java.lang.System.setProperty("user.timezone", "America/Sao_Paulo"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(CapitalizingButton_ESTest_scaffolding.class.getClassLoader() ,
      "android.os.Bundle",
      "android.view.View$AccessibilityDelegate",
      "android.content.ComponentCallbacks",
      "android.view.MotionEvent$PointerProperties",
      "android.view.TouchDelegate",
      "org.xmlpull.v1.XmlSerializer",
      "android.graphics.Bitmap$Config",
      "android.graphics.Paint$Align",
      "android.content.res.ColorStateList",
      "android.database.sqlite.SQLiteDatabase",
      "android.animation.LayoutTransition",
      "android.view.View$OnSystemUiVisibilityChangeListener",
      "android.os.Handler",
      "android.view.inputmethod.ExtractedTextRequest",
      "android.graphics.Shader",
      "org.xmlpull.v1.XmlPullParser",
      "android.database.CharArrayBuffer",
      "android.view.DragEvent",
      "android.accounts.Account",
      "android.text.TextUtils$TruncateAt",
      "android.content.IntentFilter",
      "android.view.View$OnGenericMotionListener",
      "android.view.SubMenu",
      "android.content.pm.FeatureInfo",
      "android.content.IntentFilter$AuthorityEntry",
      "android.graphics.Canvas$EdgeType",
      "android.text.Layout",
      "android.graphics.Matrix$ScaleToFit",
      "android.view.View$OnAttachStateChangeListener",
      "android.graphics.Paint",
      "android.graphics.Path",
      "android.graphics.Paint$Join",
      "android.content.IntentSender$OnFinished",
      "android.view.View$OnClickListener",
      "android.content.pm.PackageManager$NameNotFoundException",
      "android.os.RemoteException",
      "android.content.IntentFilter$MalformedMimeTypeException",
      "android.database.sqlite.SQLiteTransactionListener",
      "android.view.inputmethod.CorrectionInfo",
      "android.view.InputDevice",
      "android.view.MenuInflater",
      "android.view.ViewTreeObserver$OnPreDrawListener",
      "android.view.Menu",
      "android.graphics.Bitmap$CompressFormat",
      "android.content.res.Resources$Theme",
      "android.graphics.ColorFilter",
      "android.os.Parcelable",
      "android.text.style.URLSpan",
      "android.text.method.KeyListener",
      "android.content.ComponentName",
      "android.content.SyncInfo",
      "android.graphics.PorterDuff$Mode",
      "android.content.SharedPreferences",
      "android.view.animation.Transformation",
      "android.animation.Animator$AnimatorListener",
      "android.util.Printer",
      "android.view.View$OnCreateContextMenuListener",
      "android.view.inputmethod.CompletionInfo",
      "android.graphics.Rect",
      "android.graphics.Region$Op",
      "android.os.IBinder$DeathRecipient",
      "android.view.ActionMode",
      "android.content.pm.PackageManager",
      "android.graphics.drawable.Drawable$Callback",
      "android.text.style.ClickableSpan",
      "android.animation.Animator",
      "android.content.pm.ProviderInfo",
      "android.content.ContentResolver",
      "android.content.pm.ActivityInfo",
      "android.widget.Button",
      "android.database.DatabaseErrorHandler",
      "android.content.pm.InstrumentationInfo",
      "android.graphics.Canvas$VertexMode",
      "android.database.DataSetObserver",
      "android.view.View$OnLongClickListener",
      "android.graphics.RectF",
      "android.content.pm.PermissionGroupInfo",
      "android.util.AndroidException",
      "android.view.InputEvent",
      "android.content.pm.ComponentInfo",
      "android.util.DisplayMetrics",
      "android.os.MessageQueue$IdleHandler",
      "org.xmlpull.v1.XmlPullParserException",
      "android.view.accessibility.AccessibilityRecord",
      "android.content.ContentValues",
      "android.view.inputmethod.EditorInfo",
      "android.content.res.AssetFileDescriptor",
      "android.content.SharedPreferences$Editor",
      "android.text.Spanned",
      "android.os.Parcelable$Creator",
      "android.content.pm.PackageInfo",
      "android.text.GetChars",
      "android.view.MenuItem",
      "android.os.Build",
      "android.widget.Scroller",
      "android.graphics.MaskFilter",
      "android.view.MotionEvent$PointerCoords",
      "android.view.animation.LayoutAnimationController$AnimationParameters",
      "android.view.InputDevice$MotionRange",
      "android.view.inputmethod.ExtractedText",
      "android.content.pm.PackageItemInfo",
      "android.database.sqlite.SQLiteDatabase$CursorFactory",
      "android.graphics.Bitmap",
      "android.view.KeyCharacterMap",
      "android.view.ViewTreeObserver",
      "android.text.style.CharacterStyle",
      "android.content.ClipDescription",
      "android.content.pm.ServiceInfo",
      "android.view.View$OnHoverListener",
      "android.content.res.Resources",
      "android.view.ViewManager",
      "android.view.View$OnDragListener",
      "android.content.pm.PermissionInfo",
      "android.text.Editable$Factory",
      "android.os.ParcelFileDescriptor",
      "android.content.IntentSender$SendIntentException",
      "android.net.Uri",
      "android.view.ViewTreeObserver$OnScrollChangedListener",
      "android.graphics.Rasterizer",
      "android.graphics.drawable.Drawable",
      "android.database.sqlite.SQLiteCursorDriver",
      "android.text.method.TransformationMethod",
      "android.graphics.drawable.Drawable$ConstantState",
      "android.os.Build$VERSION",
      "android.os.Looper",
      "android.content.SyncStatusObserver",
      "android.graphics.Canvas",
      "android.net.Uri$Builder",
      "android.view.accessibility.AccessibilityEvent",
      "android.widget.TextView$BufferType",
      "android.view.animation.Interpolator",
      "android.content.res.Resources$NotFoundException",
      "android.view.KeyCharacterMap$KeyData",
      "android.graphics.Region",
      "android.view.ViewTreeObserver$OnGlobalLayoutListener",
      "android.view.View$OnLayoutChangeListener",
      "android.graphics.Paint$Cap",
      "android.content.BroadcastReceiver$PendingResult",
      "android.os.Message",
      "android.view.animation.LayoutAnimationController",
      "android.text.TextPaint",
      "android.text.InputFilter",
      "android.graphics.Xfermode",
      "android.view.accessibility.AccessibilityEventSource",
      "android.text.TextWatcher",
      "android.animation.LayoutTransition$TransitionListener",
      "android.view.ViewParent",
      "android.animation.TimeInterpolator",
      "android.text.NoCopySpan",
      "android.database.sqlite.SQLiteProgram",
      "android.graphics.PathEffect",
      "android.os.Parcel",
      "android.text.Editable",
      "android.graphics.Movie",
      "android.content.IntentSender",
      "android.text.Spannable$Factory",
      "android.content.res.AssetManager",
      "android.text.style.UpdateAppearance",
      "android.view.ViewTreeObserver$OnGlobalFocusChangeListener",
      "android.text.ParcelableSpan",
      "android.view.KeyEvent$Callback",
      "android.view.ViewGroup$OnHierarchyChangeListener",
      "android.content.OperationApplicationException",
      "android.content.ComponentCallbacks2",
      "android.text.Layout$Alignment",
      "android.util.SparseBooleanArray",
      "android.util.TypedValue",
      "android.content.res.Configuration",
      "com.actionbarsherlock.internal.widget.CapitalizingButton",
      "android.text.Spannable",
      "android.widget.RemoteViews$RemoteView",
      "android.content.res.XmlResourceParser",
      "android.os.IBinder",
      "android.view.KeyEvent$DispatcherState",
      "android.util.AttributeSet",
      "android.graphics.Paint$FontMetrics",
      "android.view.View",
      "android.content.ServiceConnection",
      "android.view.ViewTreeObserver$OnTouchModeChangeListener",
      "android.view.animation.Animation",
      "android.graphics.Matrix",
      "android.database.sqlite.SQLiteQuery",
      "android.text.method.MovementMethod",
      "android.content.ContentProviderResult",
      "android.os.Build$VERSION_CODES",
      "android.content.SharedPreferences$OnSharedPreferenceChangeListener",
      "android.view.ViewGroup$LayoutParams",
      "android.text.InputType",
      "android.content.ClipData$Item",
      "android.content.BroadcastReceiver",
      "android.view.animation.Animation$AnimationListener",
      "android.view.ViewGroup",
      "android.database.ContentObserver",
      "android.util.SparseArray",
      "android.os.MessageQueue",
      "android.widget.TextView",
      "android.os.PatternMatcher",
      "android.graphics.DrawFilter",
      "android.content.ContentProviderClient",
      "android.view.ViewPropertyAnimator",
      "android.content.pm.ApplicationInfo",
      "android.widget.TextView$OnEditorActionListener",
      "android.graphics.BitmapFactory$Options",
      "android.graphics.Typeface",
      "android.content.Context",
      "android.view.accessibility.AccessibilityNodeInfo",
      "android.view.ContextMenu",
      "android.view.KeyEvent",
      "android.view.inputmethod.InputConnection",
      "android.content.SyncAdapterType",
      "android.content.Intent",
      "android.graphics.Paint$FontMetricsInt",
      "android.content.res.TypedArray",
      "android.view.ActionMode$Callback",
      "android.content.ClipData",
      "android.graphics.Paint$Style",
      "android.view.MotionEvent",
      "android.database.sqlite.SQLiteStatement",
      "android.database.Cursor",
      "android.view.View$OnKeyListener",
      "android.os.IInterface",
      "android.graphics.Point",
      "android.database.SQLException",
      "android.content.ContentProvider",
      "android.content.pm.ResolveInfo",
      "android.view.View$DragShadowBuilder",
      "android.graphics.Picture",
      "android.text.Layout$Directions",
      "android.view.View$OnFocusChangeListener",
      "android.database.sqlite.SQLiteClosable",
      "android.view.View$OnTouchListener",
      "android.view.ContextMenu$ContextMenuInfo"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException { 
    mock(Class.forName("android.content.Context", false, CapitalizingButton_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("android.util.AttributeSet", false, CapitalizingButton_ESTest_scaffolding.class.getClassLoader()));
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(CapitalizingButton_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "android.view.View",
      "android.widget.TextView",
      "android.widget.Button",
      "android.os.Build$VERSION",
      "com.actionbarsherlock.internal.widget.CapitalizingButton",
      "android.content.Context",
      "android.view.InputEvent",
      "android.view.MotionEvent",
      "android.view.ViewGroup",
      "android.graphics.Rect",
      "android.view.inputmethod.ExtractedTextRequest",
      "android.view.inputmethod.CompletionInfo",
      "android.view.DragEvent"
    );
  }
}
