/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 05 21:54:06 GMT 2018
 */

package com.actionbarsherlock.internal.widget;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import android.content.Context;
import com.actionbarsherlock.internal.widget.IcsLinearLayout;
import com.xtremelabs.robolectric.tester.android.util.TestAttributeSet;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class IcsLinearLayout_ESTest extends IcsLinearLayout_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TestAttributeSet testAttributeSet0 = new TestAttributeSet();
      IcsLinearLayout icsLinearLayout0 = null;
      try {
        icsLinearLayout0 = new IcsLinearLayout((Context) null, testAttributeSet0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Stub!
         //
         verifyException("android.view.View", e);
      }
  }
}
