/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 05 21:51:52 GMT 2018
 */

package android.support.v4.app;

import org.junit.Test;
import static org.junit.Assert.*;
import com.actionbarsherlock.app.SherlockDialogFragment;
import com.actionbarsherlock.internal.view.menu.MenuItemWrapper;
import com.actionbarsherlock.internal.view.menu.SubMenuWrapper;
import com.actionbarsherlock.view.Menu;
import com.actionbarsherlock.view.MenuInflater;
import com.xtremelabs.robolectric.tester.android.view.TestMenuItem;
import com.xtremelabs.robolectric.tester.android.view.TestSubMenu;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class _ActionBarSherlockTrojanHorse_ESTest extends _ActionBarSherlockTrojanHorse_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SherlockDialogFragment sherlockDialogFragment0 = new SherlockDialogFragment();
      sherlockDialogFragment0.onPrepareOptionsMenu((Menu) null);
      assertFalse(sherlockDialogFragment0.isResumed());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SherlockDialogFragment sherlockDialogFragment0 = new SherlockDialogFragment();
      TestMenuItem testMenuItem0 = new TestMenuItem();
      MenuItemWrapper menuItemWrapper0 = new MenuItemWrapper(testMenuItem0);
      boolean boolean0 = sherlockDialogFragment0.onOptionsItemSelected(menuItemWrapper0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SherlockDialogFragment sherlockDialogFragment0 = new SherlockDialogFragment();
      TestSubMenu testSubMenu0 = new TestSubMenu();
      SubMenuWrapper subMenuWrapper0 = new SubMenuWrapper(testSubMenu0);
      sherlockDialogFragment0.onCreateOptionsMenu(subMenuWrapper0, (MenuInflater) null);
      assertFalse(sherlockDialogFragment0.isInLayout());
  }
}
