/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 05 22:32:07 GMT 2018
 */

package com.actionbarsherlock.internal.widget;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import android.content.Context;
import android.util.AttributeSet;
import com.actionbarsherlock.internal.widget.FakeDialogPhoneWindow;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FakeDialogPhoneWindow_ESTest extends FakeDialogPhoneWindow_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FakeDialogPhoneWindow fakeDialogPhoneWindow0 = null;
      try {
        fakeDialogPhoneWindow0 = new FakeDialogPhoneWindow((Context) null, (AttributeSet) null);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Stub!
         //
         verifyException("android.view.View", e);
      }
  }
}
