/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Mon Nov 05 22:45:43 GMT 2018
 */

package com.actionbarsherlock.app;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class SherlockFragment_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.actionbarsherlock.app.SherlockFragment"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {} 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "Cp1252"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\Thiago\\AppData\\Local\\Temp\\"); 
    java.lang.System.setProperty("user.country", "US"); 
    java.lang.System.setProperty("user.dir", "C:\\Users\\Thiago\\Documents\\Calculadora\\Calculadora-de-Tributos-PJ\\ActionBarSherlock-Library"); 
    java.lang.System.setProperty("user.home", "C:\\Users\\Thiago"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "Thiago"); 
    java.lang.System.setProperty("user.timezone", "America/Sao_Paulo"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(SherlockFragment_ESTest_scaffolding.class.getClassLoader() ,
      "android.os.Bundle",
      "android.content.IntentSender$SendIntentException",
      "android.net.Uri",
      "android.content.ComponentCallbacks",
      "android.graphics.drawable.Drawable",
      "android.view.MenuItem$OnActionExpandListener",
      "android.support.v4.app._ActionBarSherlockTrojanHorse",
      "com.actionbarsherlock.view.MenuInflater",
      "android.database.sqlite.SQLiteDatabase",
      "com.actionbarsherlock.view.SubMenu",
      "android.os.Handler",
      "android.os.Looper",
      "android.graphics.Canvas",
      "android.view.accessibility.AccessibilityEvent",
      "com.actionbarsherlock.internal.view.ActionProviderWrapper",
      "android.support.v4.app.LoaderManagerImpl",
      "org.xmlpull.v1.XmlPullParser",
      "com.actionbarsherlock.ActionBarSherlock$OnPreparePanelListener",
      "android.content.res.Resources$NotFoundException",
      "android.support.v4.app.Fragment",
      "android.content.IntentFilter",
      "android.view.SubMenu",
      "android.view.ActionProvider",
      "android.view.InflateException",
      "android.view.accessibility.AccessibilityEventSource",
      "android.app.FragmentManager",
      "android.view.ViewParent",
      "android.support.v4.app.Fragment$SavedState",
      "android.content.pm.PackageManager$NameNotFoundException",
      "com.actionbarsherlock.app.ActionBar",
      "android.content.IntentSender",
      "android.content.res.AssetManager",
      "android.view.MenuInflater",
      "android.view.Menu",
      "android.content.ContextWrapper",
      "android.content.res.Resources$Theme",
      "android.app.Fragment",
      "android.os.Parcelable",
      "com.actionbarsherlock.ActionBarSherlock$OnActionModeStartedListener",
      "android.view.KeyEvent$Callback",
      "android.support.v4.app._ActionBarSherlockTrojanHorse$OnOptionsItemSelectedListener",
      "android.content.ComponentName",
      "android.view.Window$Callback",
      "android.support.v4.app.FragmentManager",
      "android.content.ComponentCallbacks2",
      "android.support.v4.app._ActionBarSherlockTrojanHorse$OnCreateOptionsMenuListener",
      "android.content.SharedPreferences",
      "com.actionbarsherlock.view.ActionMode",
      "android.content.res.Configuration",
      "android.view.View$OnCreateContextMenuListener",
      "android.view.ActionMode",
      "android.content.pm.PackageManager",
      "android.graphics.drawable.Drawable$Callback",
      "com.actionbarsherlock.ActionBarSherlock$OnMenuItemSelectedListener",
      "android.view.WindowManager",
      "com.actionbarsherlock.app.SherlockFragment",
      "android.app.PendingIntent",
      "com.actionbarsherlock.view.MenuItem",
      "android.util.AttributeSet",
      "android.content.ContentResolver",
      "android.view.ContextThemeWrapper",
      "android.view.View",
      "android.database.DatabaseErrorHandler",
      "android.content.ServiceConnection",
      "android.view.animation.Animation",
      "android.support.v4.app.LoaderManager",
      "com.actionbarsherlock.app.SherlockFragmentActivity",
      "android.view.MenuItem$OnMenuItemClickListener",
      "android.view.ViewGroup$LayoutParams",
      "android.util.AndroidException",
      "android.view.InputEvent",
      "android.content.BroadcastReceiver",
      "android.view.ViewGroup",
      "org.xmlpull.v1.XmlPullParserException",
      "android.app.Application",
      "android.support.v4.app.FragmentActivity",
      "android.view.accessibility.AccessibilityRecord",
      "android.view.LayoutInflater$Factory2",
      "android.support.v4.app.FragmentManagerImpl",
      "android.view.Window",
      "android.content.pm.ApplicationInfo",
      "com.actionbarsherlock.internal.view.menu.MenuItemWrapper",
      "android.view.ContextMenu",
      "android.content.Context",
      "android.support.v4.app._ActionBarSherlockTrojanHorse$OnPrepareOptionsMenuListener",
      "android.view.KeyEvent",
      "android.view.LayoutInflater$Factory",
      "android.content.Intent",
      "com.actionbarsherlock.view.Menu",
      "android.view.MenuItem",
      "android.view.ActionMode$Callback",
      "android.content.res.TypedArray",
      "android.view.MotionEvent",
      "android.view.WindowManager$LayoutParams",
      "android.app.LoaderManager",
      "android.database.Cursor",
      "android.app.ActionBar",
      "android.view.LayoutInflater",
      "android.support.v4.app.Fragment$InstantiationException",
      "android.support.v4.app.FragmentActivity$1",
      "com.actionbarsherlock.view.ActionMode$Callback",
      "android.content.pm.PackageItemInfo",
      "android.database.sqlite.SQLiteDatabase$CursorFactory",
      "android.graphics.Bitmap",
      "com.actionbarsherlock.internal.view.menu.MenuWrapper",
      "com.actionbarsherlock.ActionBarSherlock$OnActionModeFinishedListener",
      "com.actionbarsherlock.ActionBarSherlock$OnCreatePanelMenuListener",
      "android.database.sqlite.SQLiteClosable",
      "android.app.Activity",
      "android.view.ContextMenu$ContextMenuInfo",
      "android.content.res.Resources",
      "android.view.ViewManager"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException { 
    mock(Class.forName("android.view.Menu", false, SherlockFragment_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("android.view.MenuInflater", false, SherlockFragment_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("android.view.MenuItem", false, SherlockFragment_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("com.actionbarsherlock.view.Menu", false, SherlockFragment_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("com.actionbarsherlock.view.MenuInflater", false, SherlockFragment_ESTest_scaffolding.class.getClassLoader()));
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(SherlockFragment_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "android.support.v4.app.Fragment",
      "com.actionbarsherlock.app.SherlockFragment",
      "com.actionbarsherlock.internal.view.menu.MenuItemWrapper",
      "com.actionbarsherlock.internal.view.menu.MenuWrapper",
      "android.view.MenuInflater",
      "com.actionbarsherlock.view.MenuInflater",
      "android.support.v4.util.DebugUtils",
      "android.content.Context",
      "com.xtremelabs.robolectric.tester.android.view.TestMenu",
      "com.xtremelabs.robolectric.tester.android.view.TestSubMenu",
      "com.xtremelabs.robolectric.tester.android.view.TestMenuItem",
      "android.content.ContextWrapper",
      "android.view.ContextThemeWrapper",
      "android.app.Activity",
      "android.accounts.AccountAuthenticatorActivity",
      "android.app.ListActivity",
      "android.support.v4.app.FragmentActivity",
      "android.support.v4.app._ActionBarSherlockTrojanHorse",
      "com.actionbarsherlock.app.SherlockFragmentActivity",
      "android.app.ExpandableListActivity",
      "android.app.AliasActivity",
      "android.view.LayoutInflater",
      "android.text.Editable$Factory",
      "com.actionbarsherlock.internal.view.menu.SubMenuWrapper",
      "android.text.SpannableStringInternal",
      "android.text.SpannableString",
      "android.app.NativeActivity",
      "android.database.AbstractCursor",
      "android.database.MatrixCursor",
      "android.app.Fragment",
      "android.app.DialogFragment",
      "android.view.accessibility.AccessibilityNodeInfo",
      "android.app.Dialog",
      "android.app.AlertDialog",
      "android.app.TimePickerDialog",
      "android.view.accessibility.AccessibilityRecord",
      "android.view.accessibility.AccessibilityEvent",
      "android.renderscript.RenderScriptGL$SurfaceConfig",
      "android.graphics.drawable.Drawable",
      "android.graphics.drawable.ShapeDrawable",
      "android.graphics.drawable.PaintDrawable",
      "android.content.ContentProvider",
      "android.content.SearchRecentSuggestionsProvider",
      "android.webkit.WebChromeClient",
      "android.net.Uri",
      "android.content.res.Resources",
      "android.text.SpannableStringBuilder",
      "android.text.method.PasswordTransformationMethod",
      "com.actionbarsherlock.internal.view.menu.MenuBuilder",
      "android.support.v4.app.Fragment$SavedState$1",
      "android.support.v4.app.Fragment$SavedState",
      "android.graphics.drawable.PictureDrawable",
      "android.graphics.Bitmap",
      "android.graphics.drawable.DrawableContainer",
      "android.graphics.drawable.StateListDrawable",
      "android.util.DisplayMetrics",
      "android.os.Looper",
      "android.view.View",
      "android.view.ViewGroup",
      "com.actionbarsherlock.internal.nineoldandroids.view.NineViewGroup",
      "android.view.animation.DecelerateInterpolator",
      "com.actionbarsherlock.internal.widget.AbsActionBarView",
      "android.content.res.Configuration",
      "android.content.pm.PackageItemInfo",
      "android.content.pm.ComponentInfo",
      "android.content.pm.ProviderInfo",
      "android.os.Bundle",
      "android.widget.LinearLayout",
      "com.actionbarsherlock.internal.view.menu.ActionMenuItemView",
      "android.graphics.drawable.AnimationDrawable",
      "android.content.Intent",
      "com.actionbarsherlock.internal.view.menu.ActionMenu",
      "com.actionbarsherlock.internal.view.menu.ActionMenuItem",
      "android.database.sqlite.SQLiteClosable",
      "android.database.sqlite.SQLiteDatabase",
      "android.os.Message",
      "android.view.inputmethod.EditorInfo",
      "android.view.inputmethod.ExtractedText",
      "com.xtremelabs.robolectric.tester.android.util.TestAttributeSet",
      "android.widget.FrameLayout",
      "android.widget.TabHost",
      "android.view.MotionEvent$PointerProperties",
      "com.xtremelabs.robolectric.res.ResourceExtractor",
      "android.content.BroadcastReceiver",
      "android.appwidget.AppWidgetProvider",
      "com.xtremelabs.robolectric.RobolectricConfig",
      "com.xtremelabs.robolectric.res.XmlLoader",
      "com.xtremelabs.robolectric.res.AttrResourceLoader",
      "com.actionbarsherlock.internal.view.menu.ListMenuItemView",
      "android.view.InputEvent",
      "android.view.MotionEvent",
      "android.app.ProgressDialog",
      "android.os.Parcel",
      "android.os.ParcelFileDescriptor",
      "android.graphics.drawable.BitmapDrawable",
      "android.text.SpannedString",
      "android.webkit.WebViewFragment",
      "com.actionbarsherlock.internal.nineoldandroids.widget.NineLinearLayout",
      "com.actionbarsherlock.internal.widget.IcsLinearLayout",
      "android.os.Build$VERSION",
      "com.actionbarsherlock.internal.view.menu.ActionMenuView",
      "android.app.ListFragment",
      "android.preference.Preference",
      "android.preference.DialogPreference",
      "android.preference.EditTextPreference",
      "android.app.ActionBar$Tab",
      "android.widget.TabWidget",
      "android.content.pm.PermissionInfo",
      "android.content.ComponentName",
      "android.content.pm.PackageManager",
      "com.xtremelabs.robolectric.tester.android.content.pm.StubPackageManager",
      "com.xtremelabs.robolectric.res.RobolectricPackageManager",
      "android.widget.TextView",
      "com.actionbarsherlock.internal.view.menu.MenuItemWrapper$1",
      "android.app.DatePickerDialog",
      "android.graphics.drawable.GradientDrawable",
      "android.view.ActionProvider",
      "android.widget.ShareActionProvider",
      "android.view.inputmethod.CompletionInfo",
      "android.media.MediaScannerConnection",
      "android.content.ClipData$Item",
      "com.actionbarsherlock.app.ActionBar",
      "com.actionbarsherlock.internal.app.ActionBarImpl",
      "android.os.Handler",
      "android.widget.RelativeLayout",
      "android.widget.DialerFilter",
      "android.view.KeyEvent",
      "android.view.MotionEvent$PointerCoords",
      "android.view.ViewGroup$LayoutParams",
      "android.view.WindowManager$LayoutParams",
      "android.graphics.drawable.LevelListDrawable",
      "android.net.http.SslCertificate",
      "android.text.InputFilter$LengthFilter",
      "android.widget.NumberPicker"
    );
  }
}
