/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Mon Nov 05 22:53:20 GMT 2018
 */

package com.actionbarsherlock.internal.widget;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class IcsView_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.actionbarsherlock.internal.widget.IcsView"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {} 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "Cp1252"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\Thiago\\AppData\\Local\\Temp\\"); 
    java.lang.System.setProperty("user.country", "US"); 
    java.lang.System.setProperty("user.dir", "C:\\Users\\Thiago\\Documents\\Calculadora\\Calculadora-de-Tributos-PJ\\ActionBarSherlock-Library"); 
    java.lang.System.setProperty("user.home", "C:\\Users\\Thiago"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "Thiago"); 
    java.lang.System.setProperty("user.timezone", "America/Sao_Paulo"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(IcsView_ESTest_scaffolding.class.getClassLoader() ,
      "android.view.View$BaseSavedState",
      "android.graphics.Rect",
      "android.view.ActionMode",
      "android.graphics.drawable.Drawable$Callback",
      "android.view.View$AccessibilityDelegate",
      "android.graphics.drawable.Drawable",
      "android.view.TouchDelegate",
      "android.view.View$MeasureSpec",
      "android.view.KeyEvent$DispatcherState",
      "android.os.IBinder",
      "android.animation.LayoutTransition",
      "android.util.AttributeSet",
      "android.view.View$OnSystemUiVisibilityChangeListener",
      "android.os.Handler",
      "android.view.View",
      "android.graphics.Canvas",
      "android.view.accessibility.AccessibilityEvent",
      "android.view.animation.Animation",
      "android.graphics.Matrix",
      "android.view.View$OnLongClickListener",
      "android.view.DragEvent",
      "android.view.ViewGroup$LayoutParams",
      "android.view.InputEvent",
      "android.text.InputType",
      "android.view.View$OnGenericMotionListener",
      "android.graphics.Region",
      "android.view.animation.Animation$AnimationListener",
      "android.view.ViewGroup",
      "android.view.View$OnLayoutChangeListener",
      "android.util.SparseArray",
      "android.view.animation.LayoutAnimationController",
      "android.view.accessibility.AccessibilityRecord",
      "android.view.View$OnAttachStateChangeListener",
      "android.graphics.Paint",
      "android.view.ViewPropertyAnimator",
      "android.view.inputmethod.EditorInfo",
      "android.view.accessibility.AccessibilityEventSource",
      "android.content.Context",
      "android.view.accessibility.AccessibilityNodeInfo",
      "android.view.ContextMenu",
      "android.view.ViewParent",
      "android.view.KeyEvent",
      "android.view.View$OnClickListener",
      "android.view.inputmethod.InputConnection",
      "android.content.res.TypedArray",
      "android.view.ActionMode$Callback",
      "android.content.ClipData",
      "android.view.MotionEvent",
      "android.view.Menu",
      "android.view.View$OnKeyListener",
      "android.os.Parcelable",
      "android.view.KeyEvent$Callback",
      "android.view.ViewGroup$OnHierarchyChangeListener",
      "android.view.AbsSavedState",
      "android.graphics.Point",
      "com.actionbarsherlock.internal.widget.IcsView",
      "android.view.View$DragShadowBuilder",
      "android.graphics.Bitmap",
      "android.content.res.Configuration",
      "android.view.ViewGroup$MarginLayoutParams",
      "android.view.View$OnFocusChangeListener",
      "android.view.ViewTreeObserver",
      "android.view.animation.Transformation",
      "android.view.View$OnHoverListener",
      "android.view.View$OnTouchListener",
      "android.view.View$OnCreateContextMenuListener",
      "android.view.ContextMenu$ContextMenuInfo",
      "android.view.ViewManager",
      "android.content.res.Resources",
      "android.view.View$OnDragListener"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException { 
    mock(Class.forName("android.view.ViewGroup", false, IcsView_ESTest_scaffolding.class.getClassLoader()));
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(IcsView_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.actionbarsherlock.internal.widget.IcsView",
      "android.content.Context",
      "android.view.View",
      "android.view.ViewGroup",
      "android.view.InputEvent",
      "android.view.KeyEvent",
      "android.graphics.Rect",
      "android.view.MotionEvent",
      "android.view.accessibility.AccessibilityRecord",
      "android.view.accessibility.AccessibilityEvent",
      "android.graphics.Paint",
      "android.content.res.Configuration",
      "android.util.SparseArray"
    );
  }
}
