/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 05 21:58:46 GMT 2018
 */

package com.actionbarsherlock.internal.view.menu;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import android.content.Context;
import android.view.View;
import com.actionbarsherlock.internal.view.menu.MenuBuilder;
import com.actionbarsherlock.internal.view.menu.MenuPopupHelper;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MenuPopupHelper_ESTest extends MenuPopupHelper_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MenuPopupHelper menuPopupHelper0 = null;
      try {
        menuPopupHelper0 = new MenuPopupHelper((Context) null, (MenuBuilder) null, (View) null, false);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Stub!
         //
         verifyException("android.view.LayoutInflater", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MenuPopupHelper menuPopupHelper0 = null;
      try {
        menuPopupHelper0 = new MenuPopupHelper((Context) null, (MenuBuilder) null, (View) null);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Stub!
         //
         verifyException("android.view.LayoutInflater", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      MenuPopupHelper menuPopupHelper0 = null;
      try {
        menuPopupHelper0 = new MenuPopupHelper((Context) null, (MenuBuilder) null);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Stub!
         //
         verifyException("android.view.LayoutInflater", e);
      }
  }
}
