/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 05 22:50:29 GMT 2018
 */

package com.actionbarsherlock.internal.view;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.actionbarsherlock.internal.view.ActionProviderWrapper;
import com.actionbarsherlock.view.ActionProvider;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ActionProviderWrapper_ESTest extends ActionProviderWrapper_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ActionProvider actionProvider0 = mock(ActionProvider.class, new ViolatedAssumptionAnswer());
      ActionProviderWrapper actionProviderWrapper0 = null;
      try {
        actionProviderWrapper0 = new ActionProviderWrapper(actionProvider0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Stub!
         //
         verifyException("android.view.ActionProvider", e);
      }
  }
}
