/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 05 22:50:47 GMT 2018
 */

package com.actionbarsherlock;

import org.junit.Test;
import static org.junit.Assert.*;
import com.actionbarsherlock.R;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class R_ESTest extends R_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      R.color r_color0 = new R.color();
      assertEquals(2131034118, R.color.abs__bright_foreground_inverse_holo_dark);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      R.style r_style0 = new R.style();
      assertEquals(2131361853, R.style.TextAppearance_Sherlock_Widget_ActionMode_Subtitle_Inverse);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      R.attr r_attr0 = new R.attr();
      assertEquals(2130772029, R.attr.subtitle);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      R.drawable r_drawable0 = new R.drawable();
      assertEquals(2130837576, R.drawable.abs__spinner_ab_disabled_holo_dark);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      R.integer r_integer0 = new R.integer();
      assertEquals(2131165184, R.integer.abs__max_action_buttons);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      R.layout r_layout0 = new R.layout();
      assertEquals(2130903055, R.layout.abs__popup_menu_item_layout);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      R.styleable r_styleable0 = new R.styleable();
      assertEquals(7, R.styleable.SherlockMenuView_preserveIconSpacing);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      R.id r_id0 = new R.id();
      assertEquals(2131230752, R.id.abs__radio);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      R.dimen r_dimen0 = new R.dimen();
      assertEquals(2131099657, R.dimen.abs__dialog_min_width_major);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      R.bool r_bool0 = new R.bool();
      assertEquals(2130968581, R.bool.abs__config_allowActionMenuItemTextWithIcon);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      R r0 = new R();
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      R.string r_string0 = new R.string();
      assertEquals(2131296261, R.string.abs__activity_chooser_view_dialog_title_default);
  }
}
