/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 05 22:52:32 GMT 2018
 */

package com.actionbarsherlock.internal.nineoldandroids.animation;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.actionbarsherlock.internal.nineoldandroids.animation.FloatEvaluator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FloatEvaluator_ESTest extends FloatEvaluator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FloatEvaluator floatEvaluator0 = new FloatEvaluator();
      Float float0 = new Float(1824.0F);
      Float float1 = floatEvaluator0.evaluate(0.0F, (Number) float0, (Number) float0);
      assertEquals(1824.0F, (float)float1, 0.01F);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      FloatEvaluator floatEvaluator0 = new FloatEvaluator();
      Float float0 = new Float(0.0F);
      Integer integer0 = new Integer(0);
      Float float1 = floatEvaluator0.evaluate(0.0F, (Number) float0, (Number) integer0);
      assertEquals(0.0F, (float)float1, 0.01F);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      FloatEvaluator floatEvaluator0 = new FloatEvaluator();
      Float float0 = new Float((-627.08169039232));
      Float float1 = new Float((-1.0F));
      Float float2 = floatEvaluator0.evaluate((-1.0F), (Number) float1, (Number) float0);
      assertEquals(625.08167F, (float)float2, 0.01F);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Double double0 = new Double((-28.173223F));
      FloatEvaluator floatEvaluator0 = new FloatEvaluator();
      Float float0 = floatEvaluator0.evaluate((-28.173223F), (Number) double0, (Number) double0);
      assertEquals((-28.173223F), (float)float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      FloatEvaluator floatEvaluator0 = new FloatEvaluator();
      // Undeclared exception!
      try { 
        floatEvaluator0.evaluate((-1877.7136F), (Number) null, (Number) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.actionbarsherlock.internal.nineoldandroids.animation.FloatEvaluator", e);
      }
  }
}
