/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 05 22:25:15 GMT 2018
 */

package com.actionbarsherlock.internal.nineoldandroids.widget;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import android.content.Context;
import com.actionbarsherlock.internal.nineoldandroids.widget.NineFrameLayout;
import com.xtremelabs.robolectric.tester.android.util.TestAttributeSet;
import java.util.HashMap;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class NineFrameLayout_ESTest extends NineFrameLayout_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      HashMap<String, String> hashMap0 = new HashMap<String, String>();
      TestAttributeSet testAttributeSet0 = new TestAttributeSet(hashMap0);
      NineFrameLayout nineFrameLayout0 = null;
      try {
        nineFrameLayout0 = new NineFrameLayout((Context) null, testAttributeSet0, 8);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Stub!
         //
         verifyException("android.view.View", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TestAttributeSet testAttributeSet0 = new TestAttributeSet();
      NineFrameLayout nineFrameLayout0 = null;
      try {
        nineFrameLayout0 = new NineFrameLayout((Context) null, testAttributeSet0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Stub!
         //
         verifyException("android.view.View", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      NineFrameLayout nineFrameLayout0 = null;
      try {
        nineFrameLayout0 = new NineFrameLayout((Context) null);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Stub!
         //
         verifyException("android.view.View", e);
      }
  }
}
