/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 05 22:49:01 GMT 2018
 */

package com.actionbarsherlock.internal.nineoldandroids.animation;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.actionbarsherlock.internal.nineoldandroids.animation.IntEvaluator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class IntEvaluator_ESTest extends IntEvaluator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      IntEvaluator intEvaluator0 = new IntEvaluator();
      Integer integer0 = new Integer(2096);
      Integer integer1 = intEvaluator0.evaluate((-1919.09F), integer0, integer0);
      assertEquals(2096, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      IntEvaluator intEvaluator0 = new IntEvaluator();
      Integer integer0 = new Integer(0);
      Integer integer1 = intEvaluator0.evaluate((-888.73F), integer0, integer0);
      assertEquals(0, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      IntEvaluator intEvaluator0 = new IntEvaluator();
      Integer integer0 = new Integer((-1));
      Integer integer1 = new Integer((-158));
      Integer integer2 = intEvaluator0.evaluate((-649.0F), integer0, integer1);
      assertEquals(101892, (int)integer2);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      IntEvaluator intEvaluator0 = new IntEvaluator();
      Integer integer0 = Integer.getInteger((String) null);
      // Undeclared exception!
      try { 
        intEvaluator0.evaluate((-484.5F), (Integer) null, integer0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.actionbarsherlock.internal.nineoldandroids.animation.IntEvaluator", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      IntEvaluator intEvaluator0 = new IntEvaluator();
      Integer integer0 = new Integer((-1));
      Integer integer1 = intEvaluator0.evaluate((-649.0F), integer0, integer0);
      assertEquals((-1), (int)integer1);
  }
}
