/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 05 22:33:20 GMT 2018
 */

package com.actionbarsherlock.internal;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import android.app.Activity;
import android.view.MenuItem;
import android.view.SubMenu;
import android.view.View;
import android.view.ViewGroup;
import com.actionbarsherlock.internal.ActionBarSherlockNative;
import com.actionbarsherlock.view.ActionMode;
import com.xtremelabs.robolectric.tester.android.view.TestSubMenu;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ActionBarSherlockNative_ESTest extends ActionBarSherlockNative_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      TestSubMenu testSubMenu0 = new TestSubMenu();
      ActionBarSherlockNative actionBarSherlockNative0 = new ActionBarSherlockNative((Activity) null, 5897);
      actionBarSherlockNative0.dispatchCreateOptionsMenu(testSubMenu0);
      boolean boolean0 = actionBarSherlockNative0.dispatchOptionsItemSelected((MenuItem) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ActionBarSherlockNative actionBarSherlockNative0 = new ActionBarSherlockNative((Activity) null, 0);
      // Undeclared exception!
      try { 
        actionBarSherlockNative0.getThemedContext();
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Stub!
         //
         verifyException("android.util.TypedValue", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ActionBarSherlockNative actionBarSherlockNative0 = new ActionBarSherlockNative((Activity) null, (-1));
      // Undeclared exception!
      try { 
        actionBarSherlockNative0.startActionMode((ActionMode.Callback) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.actionbarsherlock.internal.ActionBarSherlockNative", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      TestSubMenu testSubMenu0 = new TestSubMenu();
      SubMenu subMenu0 = testSubMenu0.addSubMenu(938);
      ActionBarSherlockNative actionBarSherlockNative0 = new ActionBarSherlockNative((Activity) null, 5885);
      actionBarSherlockNative0.dispatchCreateOptionsMenu(testSubMenu0);
      boolean boolean0 = actionBarSherlockNative0.dispatchCreateOptionsMenu(subMenu0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      TestSubMenu testSubMenu0 = new TestSubMenu();
      ActionBarSherlockNative actionBarSherlockNative0 = new ActionBarSherlockNative((Activity) null, 5897);
      actionBarSherlockNative0.dispatchCreateOptionsMenu(testSubMenu0);
      boolean boolean0 = actionBarSherlockNative0.dispatchCreateOptionsMenu(testSubMenu0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ActionBarSherlockNative actionBarSherlockNative0 = new ActionBarSherlockNative((Activity) null, 0);
      // Undeclared exception!
      try { 
        actionBarSherlockNative0.requestFeature((-1050));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.actionbarsherlock.internal.ActionBarSherlockNative", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ActionBarSherlockNative actionBarSherlockNative0 = new ActionBarSherlockNative((Activity) null, 938);
      // Undeclared exception!
      try { 
        actionBarSherlockNative0.setContentView((View) null, (ViewGroup.LayoutParams) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.actionbarsherlock.internal.ActionBarSherlockNative", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ActionBarSherlockNative actionBarSherlockNative0 = new ActionBarSherlockNative((Activity) null, 5897);
      // Undeclared exception!
      try { 
        actionBarSherlockNative0.dispatchOptionsItemSelected((MenuItem) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.actionbarsherlock.internal.ActionBarSherlockNative", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ActionBarSherlockNative actionBarSherlockNative0 = new ActionBarSherlockNative((Activity) null, 0);
      StringBuilder stringBuilder0 = new StringBuilder(1);
      // Undeclared exception!
      try { 
        actionBarSherlockNative0.setTitle((CharSequence) stringBuilder0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.actionbarsherlock.internal.ActionBarSherlockNative", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ActionBarSherlockNative actionBarSherlockNative0 = new ActionBarSherlockNative((Activity) null, 5897);
      // Undeclared exception!
      try { 
        actionBarSherlockNative0.dispatchInvalidateOptionsMenu();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.actionbarsherlock.internal.ActionBarSherlockNative", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ActionBarSherlockNative actionBarSherlockNative0 = new ActionBarSherlockNative((Activity) null, 5885);
      // Undeclared exception!
      try { 
        actionBarSherlockNative0.setSecondaryProgress(0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.actionbarsherlock.internal.ActionBarSherlockNative", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ActionBarSherlockNative actionBarSherlockNative0 = new ActionBarSherlockNative((Activity) null, (-1));
      // Undeclared exception!
      try { 
        actionBarSherlockNative0.setProgressBarIndeterminate(false);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.actionbarsherlock.internal.ActionBarSherlockNative", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      ActionBarSherlockNative actionBarSherlockNative0 = new ActionBarSherlockNative((Activity) null, 0);
      // Undeclared exception!
      try { 
        actionBarSherlockNative0.setUiOptions(0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.actionbarsherlock.internal.ActionBarSherlockNative", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      ActionBarSherlockNative actionBarSherlockNative0 = new ActionBarSherlockNative((Activity) null, 0);
      // Undeclared exception!
      try { 
        actionBarSherlockNative0.setUiOptions(0, 1333);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.actionbarsherlock.internal.ActionBarSherlockNative", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      ActionBarSherlockNative actionBarSherlockNative0 = new ActionBarSherlockNative((Activity) null, 0);
      // Undeclared exception!
      try { 
        actionBarSherlockNative0.getActionBar();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.actionbarsherlock.internal.ActionBarSherlockNative", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      ActionBarSherlockNative actionBarSherlockNative0 = new ActionBarSherlockNative((Activity) null, 16843671);
      // Undeclared exception!
      try { 
        actionBarSherlockNative0.setProgress((-1299));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.actionbarsherlock.internal.ActionBarSherlockNative", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      ActionBarSherlockNative actionBarSherlockNative0 = new ActionBarSherlockNative((Activity) null, 5894);
      // Undeclared exception!
      try { 
        actionBarSherlockNative0.hasFeature(5894);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.actionbarsherlock.internal.ActionBarSherlockNative", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      ActionBarSherlockNative actionBarSherlockNative0 = new ActionBarSherlockNative((Activity) null, (-1368));
      // Undeclared exception!
      try { 
        actionBarSherlockNative0.setContentView(191);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.actionbarsherlock.internal.ActionBarSherlockNative", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      ActionBarSherlockNative actionBarSherlockNative0 = new ActionBarSherlockNative((Activity) null, 8);
      // Undeclared exception!
      try { 
        actionBarSherlockNative0.setProgressBarVisibility(true);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.actionbarsherlock.internal.ActionBarSherlockNative", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      ActionBarSherlockNative actionBarSherlockNative0 = new ActionBarSherlockNative((Activity) null, (-177));
      // Undeclared exception!
      try { 
        actionBarSherlockNative0.setProgressBarIndeterminateVisibility(true);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.actionbarsherlock.internal.ActionBarSherlockNative", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      ActionBarSherlockNative actionBarSherlockNative0 = new ActionBarSherlockNative((Activity) null, 0);
      TestSubMenu testSubMenu0 = new TestSubMenu();
      boolean boolean0 = actionBarSherlockNative0.dispatchPrepareOptionsMenu(testSubMenu0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      ActionBarSherlockNative actionBarSherlockNative0 = new ActionBarSherlockNative((Activity) null, 716);
      ActionMode.Callback actionMode_Callback0 = mock(ActionMode.Callback.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        actionBarSherlockNative0.startActionMode(actionMode_Callback0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.actionbarsherlock.internal.ActionBarSherlockNative", e);
      }
  }
}
